// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: monitor/v1/counter.proto

package com.didiyun.monitor.v1;

public interface CounterInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.monitor.v1.CounterInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *数据类型，"GAUGE"或者"COUNTER"等
   * </pre>
   *
   * <code>string dstype = 1;</code>
   * @return The dstype.
   */
  java.lang.String getDstype();
  /**
   * <pre>
   *数据类型，"GAUGE"或者"COUNTER"等
   * </pre>
   *
   * <code>string dstype = 1;</code>
   * @return The bytes for dstype.
   */
  com.google.protobuf.ByteString
      getDstypeBytes();

  /**
   * <pre>
   *数据步长，单位为秒
   * </pre>
   *
   * <code>int32 step = 2;</code>
   * @return The step.
   */
  int getStep();

  /**
   * <pre>
   *查询的监控tag名称
   * </pre>
   *
   * <code>string monitorTags = 3;</code>
   * @return The monitorTags.
   */
  java.lang.String getMonitorTags();
  /**
   * <pre>
   *查询的监控tag名称
   * </pre>
   *
   * <code>string monitorTags = 3;</code>
   * @return The bytes for monitorTags.
   */
  com.google.protobuf.ByteString
      getMonitorTagsBytes();
}
