// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: monitor/v1/counter.proto

package com.didiyun.monitor.v1;

public interface CounterResourceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.monitor.v1.CounterResource)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *查询的资源Uuid列表
   * </pre>
   *
   * <code>repeated string resourceUuids = 1;</code>
   * @return A list containing the resourceUuids.
   */
  java.util.List<java.lang.String>
      getResourceUuidsList();
  /**
   * <pre>
   *查询的资源Uuid列表
   * </pre>
   *
   * <code>repeated string resourceUuids = 1;</code>
   * @return The count of resourceUuids.
   */
  int getResourceUuidsCount();
  /**
   * <pre>
   *查询的资源Uuid列表
   * </pre>
   *
   * <code>repeated string resourceUuids = 1;</code>
   * @param index The index of the element to return.
   * @return The resourceUuids at the given index.
   */
  java.lang.String getResourceUuids(int index);
  /**
   * <pre>
   *查询的资源Uuid列表
   * </pre>
   *
   * <code>repeated string resourceUuids = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the resourceUuids at the given index.
   */
  com.google.protobuf.ByteString
      getResourceUuidsBytes(int index);

  /**
   * <pre>
   *查询的资源类型
   * </pre>
   *
   * <code>string resourceType = 2;</code>
   * @return The resourceType.
   */
  java.lang.String getResourceType();
  /**
   * <pre>
   *查询的资源类型
   * </pre>
   *
   * <code>string resourceType = 2;</code>
   * @return The bytes for resourceType.
   */
  com.google.protobuf.ByteString
      getResourceTypeBytes();

  /**
   * <pre>
   *查询的监控指标名
   * </pre>
   *
   * <code>repeated string metric = 3;</code>
   * @return A list containing the metric.
   */
  java.util.List<java.lang.String>
      getMetricList();
  /**
   * <pre>
   *查询的监控指标名
   * </pre>
   *
   * <code>repeated string metric = 3;</code>
   * @return The count of metric.
   */
  int getMetricCount();
  /**
   * <pre>
   *查询的监控指标名
   * </pre>
   *
   * <code>repeated string metric = 3;</code>
   * @param index The index of the element to return.
   * @return The metric at the given index.
   */
  java.lang.String getMetric(int index);
  /**
   * <pre>
   *查询的监控指标名
   * </pre>
   *
   * <code>repeated string metric = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the metric at the given index.
   */
  com.google.protobuf.ByteString
      getMetricBytes(int index);
}
