// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: monitor/v1/counter.proto

package com.didiyun.monitor.v1;

public interface CounterOutputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.monitor.v1.CounterOutput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *资源uuid
   * </pre>
   *
   * <code>string resourceUuid = 1;</code>
   * @return The resourceUuid.
   */
  java.lang.String getResourceUuid();
  /**
   * <pre>
   *资源uuid
   * </pre>
   *
   * <code>string resourceUuid = 1;</code>
   * @return The bytes for resourceUuid.
   */
  com.google.protobuf.ByteString
      getResourceUuidBytes();

  /**
   * <pre>
   *资源类型
   * </pre>
   *
   * <code>string resourceType = 2;</code>
   * @return The resourceType.
   */
  java.lang.String getResourceType();
  /**
   * <pre>
   *资源类型
   * </pre>
   *
   * <code>string resourceType = 2;</code>
   * @return The bytes for resourceType.
   */
  com.google.protobuf.ByteString
      getResourceTypeBytes();

  /**
   * <pre>
   *此资源上报所用的别名
   * </pre>
   *
   * <code>string alias = 3;</code>
   * @return The alias.
   */
  java.lang.String getAlias();
  /**
   * <pre>
   *此资源上报所用的别名
   * </pre>
   *
   * <code>string alias = 3;</code>
   * @return The bytes for alias.
   */
  com.google.protobuf.ByteString
      getAliasBytes();

  /**
   * <pre>
   *此资源支持的曲线
   * </pre>
   *
   * <code>repeated .didi.cloud.monitor.v1.CounterInfo counters = 4;</code>
   */
  java.util.List<com.didiyun.monitor.v1.CounterInfo> 
      getCountersList();
  /**
   * <pre>
   *此资源支持的曲线
   * </pre>
   *
   * <code>repeated .didi.cloud.monitor.v1.CounterInfo counters = 4;</code>
   */
  com.didiyun.monitor.v1.CounterInfo getCounters(int index);
  /**
   * <pre>
   *此资源支持的曲线
   * </pre>
   *
   * <code>repeated .didi.cloud.monitor.v1.CounterInfo counters = 4;</code>
   */
  int getCountersCount();
  /**
   * <pre>
   *此资源支持的曲线
   * </pre>
   *
   * <code>repeated .didi.cloud.monitor.v1.CounterInfo counters = 4;</code>
   */
  java.util.List<? extends com.didiyun.monitor.v1.CounterInfoOrBuilder> 
      getCountersOrBuilderList();
  /**
   * <pre>
   *此资源支持的曲线
   * </pre>
   *
   * <code>repeated .didi.cloud.monitor.v1.CounterInfo counters = 4;</code>
   */
  com.didiyun.monitor.v1.CounterInfoOrBuilder getCountersOrBuilder(
      int index);

  /**
   * <pre>
   *监控指标名
   * </pre>
   *
   * <code>string metric = 5;</code>
   * @return The metric.
   */
  java.lang.String getMetric();
  /**
   * <pre>
   *监控指标名
   * </pre>
   *
   * <code>string metric = 5;</code>
   * @return The bytes for metric.
   */
  com.google.protobuf.ByteString
      getMetricBytes();

  /**
   * <pre>
   *监控指标中文别名
   * </pre>
   *
   * <code>string metricAlias = 6;</code>
   * @return The metricAlias.
   */
  java.lang.String getMetricAlias();
  /**
   * <pre>
   *监控指标中文别名
   * </pre>
   *
   * <code>string metricAlias = 6;</code>
   * @return The bytes for metricAlias.
   */
  com.google.protobuf.ByteString
      getMetricAliasBytes();
}
