// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill/v1/bill.proto

package com.didiyun.bill.v1;

/**
 * Protobuf type {@code didi.cloud.bill.v1.BuyDetail}
 */
public  final class BuyDetail extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:didi.cloud.bill.v1.BuyDetail)
    BuyDetailOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BuyDetail.newBuilder() to construct.
  private BuyDetail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BuyDetail() {
    volumeUnitDescribe_ = "";
    range_ = emptyLongList();
    in_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BuyDetail();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BuyDetail(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            unitVolume_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            volumeUnitDescribe_ = s;
            break;
          }
          case 24: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              range_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            range_.addLong(input.readInt64());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              range_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              range_.addLong(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 32: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              in_ = newLongList();
              mutable_bitField0_ |= 0x00000002;
            }
            in_.addLong(input.readInt64());
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
              in_ = newLongList();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              in_.addLong(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 41: {

            unitPrice_ = input.readDouble();
            break;
          }
          case 48: {

            value_ = input.readInt64();
            break;
          }
          case 57: {

            realPrice_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        range_.makeImmutable(); // C
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        in_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.didiyun.bill.v1.BillOuterClass.internal_static_didi_cloud_bill_v1_BuyDetail_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.didiyun.bill.v1.BillOuterClass.internal_static_didi_cloud_bill_v1_BuyDetail_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.didiyun.bill.v1.BuyDetail.class, com.didiyun.bill.v1.BuyDetail.Builder.class);
  }

  public static final int UNITVOLUME_FIELD_NUMBER = 1;
  private long unitVolume_;
  /**
   * <pre>
   *计费因子的单位，例如86400，如volumeUnitDescribe 为“seconds”，则代表86400秒
   * </pre>
   *
   * <code>int64 unitVolume = 1;</code>
   * @return The unitVolume.
   */
  public long getUnitVolume() {
    return unitVolume_;
  }

  public static final int VOLUMEUNITDESCRIBE_FIELD_NUMBER = 2;
  private volatile java.lang.Object volumeUnitDescribe_;
  /**
   * <pre>
   *单位的描述，如 “seconds”、“gigabyte”
   * </pre>
   *
   * <code>string volumeUnitDescribe = 2;</code>
   * @return The volumeUnitDescribe.
   */
  public java.lang.String getVolumeUnitDescribe() {
    java.lang.Object ref = volumeUnitDescribe_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      volumeUnitDescribe_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *单位的描述，如 “seconds”、“gigabyte”
   * </pre>
   *
   * <code>string volumeUnitDescribe = 2;</code>
   * @return The bytes for volumeUnitDescribe.
   */
  public com.google.protobuf.ByteString
      getVolumeUnitDescribeBytes() {
    java.lang.Object ref = volumeUnitDescribe_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      volumeUnitDescribe_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RANGE_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.LongList range_;
  /**
   * <pre>
   *value的取值范围 value * unitvolume为此factor的规格描述
   * </pre>
   *
   * <code>repeated int64 range = 3;</code>
   * @return A list containing the range.
   */
  public java.util.List<java.lang.Long>
      getRangeList() {
    return range_;
  }
  /**
   * <pre>
   *value的取值范围 value * unitvolume为此factor的规格描述
   * </pre>
   *
   * <code>repeated int64 range = 3;</code>
   * @return The count of range.
   */
  public int getRangeCount() {
    return range_.size();
  }
  /**
   * <pre>
   *value的取值范围 value * unitvolume为此factor的规格描述
   * </pre>
   *
   * <code>repeated int64 range = 3;</code>
   * @param index The index of the element to return.
   * @return The range at the given index.
   */
  public long getRange(int index) {
    return range_.getLong(index);
  }
  private int rangeMemoizedSerializedSize = -1;

  public static final int IN_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.LongList in_;
  /**
   * <pre>
   *与range互斥，range的离散表示
   * </pre>
   *
   * <code>repeated int64 in = 4;</code>
   * @return A list containing the in.
   */
  public java.util.List<java.lang.Long>
      getInList() {
    return in_;
  }
  /**
   * <pre>
   *与range互斥，range的离散表示
   * </pre>
   *
   * <code>repeated int64 in = 4;</code>
   * @return The count of in.
   */
  public int getInCount() {
    return in_.size();
  }
  /**
   * <pre>
   *与range互斥，range的离散表示
   * </pre>
   *
   * <code>repeated int64 in = 4;</code>
   * @param index The index of the element to return.
   * @return The in at the given index.
   */
  public long getIn(int index) {
    return in_.getLong(index);
  }
  private int inMemoizedSerializedSize = -1;

  public static final int UNITPRICE_FIELD_NUMBER = 5;
  private double unitPrice_;
  /**
   * <pre>
   *在unitVolume给定的情况下，相应的unitvolume下的价格
   * </pre>
   *
   * <code>double unitPrice = 5;</code>
   * @return The unitPrice.
   */
  public double getUnitPrice() {
    return unitPrice_;
  }

  public static final int VALUE_FIELD_NUMBER = 6;
  private long value_;
  /**
   * <pre>
   *value * unitvolume为此factor的规格描述 例：描述内存为每1G下的价格为0.8元，内存取值为0~32，则unitVolume为1，VolumeUnitDescribe
   * </pre>
   *
   * <code>int64 value = 6;</code>
   * @return The value.
   */
  public long getValue() {
    return value_;
  }

  public static final int REALPRICE_FIELD_NUMBER = 7;
  private double realPrice_;
  /**
   * <pre>
   *实际扣费
   * </pre>
   *
   * <code>double realPrice = 7;</code>
   * @return The realPrice.
   */
  public double getRealPrice() {
    return realPrice_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (unitVolume_ != 0L) {
      output.writeInt64(1, unitVolume_);
    }
    if (!getVolumeUnitDescribeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, volumeUnitDescribe_);
    }
    if (getRangeList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(rangeMemoizedSerializedSize);
    }
    for (int i = 0; i < range_.size(); i++) {
      output.writeInt64NoTag(range_.getLong(i));
    }
    if (getInList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(inMemoizedSerializedSize);
    }
    for (int i = 0; i < in_.size(); i++) {
      output.writeInt64NoTag(in_.getLong(i));
    }
    if (unitPrice_ != 0D) {
      output.writeDouble(5, unitPrice_);
    }
    if (value_ != 0L) {
      output.writeInt64(6, value_);
    }
    if (realPrice_ != 0D) {
      output.writeDouble(7, realPrice_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (unitVolume_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, unitVolume_);
    }
    if (!getVolumeUnitDescribeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, volumeUnitDescribe_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < range_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(range_.getLong(i));
      }
      size += dataSize;
      if (!getRangeList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      rangeMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < in_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(in_.getLong(i));
      }
      size += dataSize;
      if (!getInList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      inMemoizedSerializedSize = dataSize;
    }
    if (unitPrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, unitPrice_);
    }
    if (value_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, value_);
    }
    if (realPrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, realPrice_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.didiyun.bill.v1.BuyDetail)) {
      return super.equals(obj);
    }
    com.didiyun.bill.v1.BuyDetail other = (com.didiyun.bill.v1.BuyDetail) obj;

    if (getUnitVolume()
        != other.getUnitVolume()) return false;
    if (!getVolumeUnitDescribe()
        .equals(other.getVolumeUnitDescribe())) return false;
    if (!getRangeList()
        .equals(other.getRangeList())) return false;
    if (!getInList()
        .equals(other.getInList())) return false;
    if (java.lang.Double.doubleToLongBits(getUnitPrice())
        != java.lang.Double.doubleToLongBits(
            other.getUnitPrice())) return false;
    if (getValue()
        != other.getValue()) return false;
    if (java.lang.Double.doubleToLongBits(getRealPrice())
        != java.lang.Double.doubleToLongBits(
            other.getRealPrice())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UNITVOLUME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUnitVolume());
    hash = (37 * hash) + VOLUMEUNITDESCRIBE_FIELD_NUMBER;
    hash = (53 * hash) + getVolumeUnitDescribe().hashCode();
    if (getRangeCount() > 0) {
      hash = (37 * hash) + RANGE_FIELD_NUMBER;
      hash = (53 * hash) + getRangeList().hashCode();
    }
    if (getInCount() > 0) {
      hash = (37 * hash) + IN_FIELD_NUMBER;
      hash = (53 * hash) + getInList().hashCode();
    }
    hash = (37 * hash) + UNITPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getUnitPrice()));
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getValue());
    hash = (37 * hash) + REALPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRealPrice()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.didiyun.bill.v1.BuyDetail parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.bill.v1.BuyDetail parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.bill.v1.BuyDetail parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.bill.v1.BuyDetail parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.bill.v1.BuyDetail parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.bill.v1.BuyDetail parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.bill.v1.BuyDetail parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.didiyun.bill.v1.BuyDetail parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.didiyun.bill.v1.BuyDetail parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.didiyun.bill.v1.BuyDetail parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.didiyun.bill.v1.BuyDetail parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.didiyun.bill.v1.BuyDetail parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.didiyun.bill.v1.BuyDetail prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code didi.cloud.bill.v1.BuyDetail}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:didi.cloud.bill.v1.BuyDetail)
      com.didiyun.bill.v1.BuyDetailOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.didiyun.bill.v1.BillOuterClass.internal_static_didi_cloud_bill_v1_BuyDetail_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.didiyun.bill.v1.BillOuterClass.internal_static_didi_cloud_bill_v1_BuyDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.didiyun.bill.v1.BuyDetail.class, com.didiyun.bill.v1.BuyDetail.Builder.class);
    }

    // Construct using com.didiyun.bill.v1.BuyDetail.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      unitVolume_ = 0L;

      volumeUnitDescribe_ = "";

      range_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      in_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000002);
      unitPrice_ = 0D;

      value_ = 0L;

      realPrice_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.didiyun.bill.v1.BillOuterClass.internal_static_didi_cloud_bill_v1_BuyDetail_descriptor;
    }

    @java.lang.Override
    public com.didiyun.bill.v1.BuyDetail getDefaultInstanceForType() {
      return com.didiyun.bill.v1.BuyDetail.getDefaultInstance();
    }

    @java.lang.Override
    public com.didiyun.bill.v1.BuyDetail build() {
      com.didiyun.bill.v1.BuyDetail result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.didiyun.bill.v1.BuyDetail buildPartial() {
      com.didiyun.bill.v1.BuyDetail result = new com.didiyun.bill.v1.BuyDetail(this);
      int from_bitField0_ = bitField0_;
      result.unitVolume_ = unitVolume_;
      result.volumeUnitDescribe_ = volumeUnitDescribe_;
      if (((bitField0_ & 0x00000001) != 0)) {
        range_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.range_ = range_;
      if (((bitField0_ & 0x00000002) != 0)) {
        in_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.in_ = in_;
      result.unitPrice_ = unitPrice_;
      result.value_ = value_;
      result.realPrice_ = realPrice_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.didiyun.bill.v1.BuyDetail) {
        return mergeFrom((com.didiyun.bill.v1.BuyDetail)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.didiyun.bill.v1.BuyDetail other) {
      if (other == com.didiyun.bill.v1.BuyDetail.getDefaultInstance()) return this;
      if (other.getUnitVolume() != 0L) {
        setUnitVolume(other.getUnitVolume());
      }
      if (!other.getVolumeUnitDescribe().isEmpty()) {
        volumeUnitDescribe_ = other.volumeUnitDescribe_;
        onChanged();
      }
      if (!other.range_.isEmpty()) {
        if (range_.isEmpty()) {
          range_ = other.range_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureRangeIsMutable();
          range_.addAll(other.range_);
        }
        onChanged();
      }
      if (!other.in_.isEmpty()) {
        if (in_.isEmpty()) {
          in_ = other.in_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureInIsMutable();
          in_.addAll(other.in_);
        }
        onChanged();
      }
      if (other.getUnitPrice() != 0D) {
        setUnitPrice(other.getUnitPrice());
      }
      if (other.getValue() != 0L) {
        setValue(other.getValue());
      }
      if (other.getRealPrice() != 0D) {
        setRealPrice(other.getRealPrice());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.didiyun.bill.v1.BuyDetail parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.didiyun.bill.v1.BuyDetail) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long unitVolume_ ;
    /**
     * <pre>
     *计费因子的单位，例如86400，如volumeUnitDescribe 为“seconds”，则代表86400秒
     * </pre>
     *
     * <code>int64 unitVolume = 1;</code>
     * @return The unitVolume.
     */
    public long getUnitVolume() {
      return unitVolume_;
    }
    /**
     * <pre>
     *计费因子的单位，例如86400，如volumeUnitDescribe 为“seconds”，则代表86400秒
     * </pre>
     *
     * <code>int64 unitVolume = 1;</code>
     * @param value The unitVolume to set.
     * @return This builder for chaining.
     */
    public Builder setUnitVolume(long value) {
      
      unitVolume_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *计费因子的单位，例如86400，如volumeUnitDescribe 为“seconds”，则代表86400秒
     * </pre>
     *
     * <code>int64 unitVolume = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnitVolume() {
      
      unitVolume_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object volumeUnitDescribe_ = "";
    /**
     * <pre>
     *单位的描述，如 “seconds”、“gigabyte”
     * </pre>
     *
     * <code>string volumeUnitDescribe = 2;</code>
     * @return The volumeUnitDescribe.
     */
    public java.lang.String getVolumeUnitDescribe() {
      java.lang.Object ref = volumeUnitDescribe_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        volumeUnitDescribe_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *单位的描述，如 “seconds”、“gigabyte”
     * </pre>
     *
     * <code>string volumeUnitDescribe = 2;</code>
     * @return The bytes for volumeUnitDescribe.
     */
    public com.google.protobuf.ByteString
        getVolumeUnitDescribeBytes() {
      java.lang.Object ref = volumeUnitDescribe_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        volumeUnitDescribe_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *单位的描述，如 “seconds”、“gigabyte”
     * </pre>
     *
     * <code>string volumeUnitDescribe = 2;</code>
     * @param value The volumeUnitDescribe to set.
     * @return This builder for chaining.
     */
    public Builder setVolumeUnitDescribe(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      volumeUnitDescribe_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *单位的描述，如 “seconds”、“gigabyte”
     * </pre>
     *
     * <code>string volumeUnitDescribe = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVolumeUnitDescribe() {
      
      volumeUnitDescribe_ = getDefaultInstance().getVolumeUnitDescribe();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *单位的描述，如 “seconds”、“gigabyte”
     * </pre>
     *
     * <code>string volumeUnitDescribe = 2;</code>
     * @param value The bytes for volumeUnitDescribe to set.
     * @return This builder for chaining.
     */
    public Builder setVolumeUnitDescribeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      volumeUnitDescribe_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList range_ = emptyLongList();
    private void ensureRangeIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        range_ = mutableCopy(range_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     *value的取值范围 value * unitvolume为此factor的规格描述
     * </pre>
     *
     * <code>repeated int64 range = 3;</code>
     * @return A list containing the range.
     */
    public java.util.List<java.lang.Long>
        getRangeList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(range_) : range_;
    }
    /**
     * <pre>
     *value的取值范围 value * unitvolume为此factor的规格描述
     * </pre>
     *
     * <code>repeated int64 range = 3;</code>
     * @return The count of range.
     */
    public int getRangeCount() {
      return range_.size();
    }
    /**
     * <pre>
     *value的取值范围 value * unitvolume为此factor的规格描述
     * </pre>
     *
     * <code>repeated int64 range = 3;</code>
     * @param index The index of the element to return.
     * @return The range at the given index.
     */
    public long getRange(int index) {
      return range_.getLong(index);
    }
    /**
     * <pre>
     *value的取值范围 value * unitvolume为此factor的规格描述
     * </pre>
     *
     * <code>repeated int64 range = 3;</code>
     * @param index The index to set the value at.
     * @param value The range to set.
     * @return This builder for chaining.
     */
    public Builder setRange(
        int index, long value) {
      ensureRangeIsMutable();
      range_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *value的取值范围 value * unitvolume为此factor的规格描述
     * </pre>
     *
     * <code>repeated int64 range = 3;</code>
     * @param value The range to add.
     * @return This builder for chaining.
     */
    public Builder addRange(long value) {
      ensureRangeIsMutable();
      range_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *value的取值范围 value * unitvolume为此factor的规格描述
     * </pre>
     *
     * <code>repeated int64 range = 3;</code>
     * @param values The range to add.
     * @return This builder for chaining.
     */
    public Builder addAllRange(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureRangeIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, range_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *value的取值范围 value * unitvolume为此factor的规格描述
     * </pre>
     *
     * <code>repeated int64 range = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRange() {
      range_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList in_ = emptyLongList();
    private void ensureInIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        in_ = mutableCopy(in_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     *与range互斥，range的离散表示
     * </pre>
     *
     * <code>repeated int64 in = 4;</code>
     * @return A list containing the in.
     */
    public java.util.List<java.lang.Long>
        getInList() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(in_) : in_;
    }
    /**
     * <pre>
     *与range互斥，range的离散表示
     * </pre>
     *
     * <code>repeated int64 in = 4;</code>
     * @return The count of in.
     */
    public int getInCount() {
      return in_.size();
    }
    /**
     * <pre>
     *与range互斥，range的离散表示
     * </pre>
     *
     * <code>repeated int64 in = 4;</code>
     * @param index The index of the element to return.
     * @return The in at the given index.
     */
    public long getIn(int index) {
      return in_.getLong(index);
    }
    /**
     * <pre>
     *与range互斥，range的离散表示
     * </pre>
     *
     * <code>repeated int64 in = 4;</code>
     * @param index The index to set the value at.
     * @param value The in to set.
     * @return This builder for chaining.
     */
    public Builder setIn(
        int index, long value) {
      ensureInIsMutable();
      in_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *与range互斥，range的离散表示
     * </pre>
     *
     * <code>repeated int64 in = 4;</code>
     * @param value The in to add.
     * @return This builder for chaining.
     */
    public Builder addIn(long value) {
      ensureInIsMutable();
      in_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *与range互斥，range的离散表示
     * </pre>
     *
     * <code>repeated int64 in = 4;</code>
     * @param values The in to add.
     * @return This builder for chaining.
     */
    public Builder addAllIn(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureInIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, in_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *与range互斥，range的离散表示
     * </pre>
     *
     * <code>repeated int64 in = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIn() {
      in_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private double unitPrice_ ;
    /**
     * <pre>
     *在unitVolume给定的情况下，相应的unitvolume下的价格
     * </pre>
     *
     * <code>double unitPrice = 5;</code>
     * @return The unitPrice.
     */
    public double getUnitPrice() {
      return unitPrice_;
    }
    /**
     * <pre>
     *在unitVolume给定的情况下，相应的unitvolume下的价格
     * </pre>
     *
     * <code>double unitPrice = 5;</code>
     * @param value The unitPrice to set.
     * @return This builder for chaining.
     */
    public Builder setUnitPrice(double value) {
      
      unitPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *在unitVolume给定的情况下，相应的unitvolume下的价格
     * </pre>
     *
     * <code>double unitPrice = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnitPrice() {
      
      unitPrice_ = 0D;
      onChanged();
      return this;
    }

    private long value_ ;
    /**
     * <pre>
     *value * unitvolume为此factor的规格描述 例：描述内存为每1G下的价格为0.8元，内存取值为0~32，则unitVolume为1，VolumeUnitDescribe
     * </pre>
     *
     * <code>int64 value = 6;</code>
     * @return The value.
     */
    public long getValue() {
      return value_;
    }
    /**
     * <pre>
     *value * unitvolume为此factor的规格描述 例：描述内存为每1G下的价格为0.8元，内存取值为0~32，则unitVolume为1，VolumeUnitDescribe
     * </pre>
     *
     * <code>int64 value = 6;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(long value) {
      
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *value * unitvolume为此factor的规格描述 例：描述内存为每1G下的价格为0.8元，内存取值为0~32，则unitVolume为1，VolumeUnitDescribe
     * </pre>
     *
     * <code>int64 value = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      
      value_ = 0L;
      onChanged();
      return this;
    }

    private double realPrice_ ;
    /**
     * <pre>
     *实际扣费
     * </pre>
     *
     * <code>double realPrice = 7;</code>
     * @return The realPrice.
     */
    public double getRealPrice() {
      return realPrice_;
    }
    /**
     * <pre>
     *实际扣费
     * </pre>
     *
     * <code>double realPrice = 7;</code>
     * @param value The realPrice to set.
     * @return This builder for chaining.
     */
    public Builder setRealPrice(double value) {
      
      realPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *实际扣费
     * </pre>
     *
     * <code>double realPrice = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearRealPrice() {
      
      realPrice_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:didi.cloud.bill.v1.BuyDetail)
  }

  // @@protoc_insertion_point(class_scope:didi.cloud.bill.v1.BuyDetail)
  private static final com.didiyun.bill.v1.BuyDetail DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.didiyun.bill.v1.BuyDetail();
  }

  public static com.didiyun.bill.v1.BuyDetail getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BuyDetail>
      PARSER = new com.google.protobuf.AbstractParser<BuyDetail>() {
    @java.lang.Override
    public BuyDetail parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BuyDetail(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BuyDetail> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BuyDetail> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.didiyun.bill.v1.BuyDetail getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

