// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill/v1/bill.proto

package com.didiyun.bill.v1;

public interface BuyDetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.bill.v1.BuyDetail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *计费因子的单位，例如86400，如volumeUnitDescribe 为“seconds”，则代表86400秒
   * </pre>
   *
   * <code>int64 unitVolume = 1;</code>
   * @return The unitVolume.
   */
  long getUnitVolume();

  /**
   * <pre>
   *单位的描述，如 “seconds”、“gigabyte”
   * </pre>
   *
   * <code>string volumeUnitDescribe = 2;</code>
   * @return The volumeUnitDescribe.
   */
  java.lang.String getVolumeUnitDescribe();
  /**
   * <pre>
   *单位的描述，如 “seconds”、“gigabyte”
   * </pre>
   *
   * <code>string volumeUnitDescribe = 2;</code>
   * @return The bytes for volumeUnitDescribe.
   */
  com.google.protobuf.ByteString
      getVolumeUnitDescribeBytes();

  /**
   * <pre>
   *value的取值范围 value * unitvolume为此factor的规格描述
   * </pre>
   *
   * <code>repeated int64 range = 3;</code>
   * @return A list containing the range.
   */
  java.util.List<java.lang.Long> getRangeList();
  /**
   * <pre>
   *value的取值范围 value * unitvolume为此factor的规格描述
   * </pre>
   *
   * <code>repeated int64 range = 3;</code>
   * @return The count of range.
   */
  int getRangeCount();
  /**
   * <pre>
   *value的取值范围 value * unitvolume为此factor的规格描述
   * </pre>
   *
   * <code>repeated int64 range = 3;</code>
   * @param index The index of the element to return.
   * @return The range at the given index.
   */
  long getRange(int index);

  /**
   * <pre>
   *与range互斥，range的离散表示
   * </pre>
   *
   * <code>repeated int64 in = 4;</code>
   * @return A list containing the in.
   */
  java.util.List<java.lang.Long> getInList();
  /**
   * <pre>
   *与range互斥，range的离散表示
   * </pre>
   *
   * <code>repeated int64 in = 4;</code>
   * @return The count of in.
   */
  int getInCount();
  /**
   * <pre>
   *与range互斥，range的离散表示
   * </pre>
   *
   * <code>repeated int64 in = 4;</code>
   * @param index The index of the element to return.
   * @return The in at the given index.
   */
  long getIn(int index);

  /**
   * <pre>
   *在unitVolume给定的情况下，相应的unitvolume下的价格
   * </pre>
   *
   * <code>double unitPrice = 5;</code>
   * @return The unitPrice.
   */
  double getUnitPrice();

  /**
   * <pre>
   *value * unitvolume为此factor的规格描述 例：描述内存为每1G下的价格为0.8元，内存取值为0~32，则unitVolume为1，VolumeUnitDescribe
   * </pre>
   *
   * <code>int64 value = 6;</code>
   * @return The value.
   */
  long getValue();

  /**
   * <pre>
   *实际扣费
   * </pre>
   *
   * <code>double realPrice = 7;</code>
   * @return The realPrice.
   */
  double getRealPrice();
}
