// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill/v1/bill.proto

package com.didiyun.bill.v1;

public interface ChangeExpireStrategyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.bill.v1.ChangeExpireStrategyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *没有data
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Error error = 1;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <pre>
   *没有data
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Error error = 1;</code>
   * @return The error.
   */
  com.didiyun.base.v1.Error getError();
  /**
   * <pre>
   *没有data
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Error error = 1;</code>
   */
  com.didiyun.base.v1.ErrorOrBuilder getErrorOrBuilder();
}
