// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill/v1/bill.proto

package com.didiyun.bill.v1;

public interface CheckEipPriceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.bill.v1.CheckEipPriceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   * @return The header.
   */
  com.didiyun.base.v1.Header getHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  com.didiyun.base.v1.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>bool checkCoupon = 2;</code>
   * @return The checkCoupon.
   */
  boolean getCheckCoupon();

  /**
   * <code>bool isChange = 3;</code>
   * @return The isChange.
   */
  boolean getIsChange();

  /**
   * <code>.didi.cloud.bill.v1.CheckEipPriceInput eipGoods = 4;</code>
   * @return Whether the eipGoods field is set.
   */
  boolean hasEipGoods();
  /**
   * <code>.didi.cloud.bill.v1.CheckEipPriceInput eipGoods = 4;</code>
   * @return The eipGoods.
   */
  com.didiyun.bill.v1.CheckEipPriceInput getEipGoods();
  /**
   * <code>.didi.cloud.bill.v1.CheckEipPriceInput eipGoods = 4;</code>
   */
  com.didiyun.bill.v1.CheckEipPriceInputOrBuilder getEipGoodsOrBuilder();
}
