// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill/v1/bill.proto

package com.didiyun.bill.v1;

public interface CheckDc2PriceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.bill.v1.CheckDc2PriceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   * @return The header.
   */
  com.didiyun.base.v1.Header getHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  com.didiyun.base.v1.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>bool checkCoupon = 2;</code>
   * @return The checkCoupon.
   */
  boolean getCheckCoupon();

  /**
   * <code>bool isChange = 3;</code>
   * @return The isChange.
   */
  boolean getIsChange();

  /**
   * <code>.didi.cloud.bill.v1.CheckDc2PriceInput dc2Goods = 4;</code>
   * @return Whether the dc2Goods field is set.
   */
  boolean hasDc2Goods();
  /**
   * <code>.didi.cloud.bill.v1.CheckDc2PriceInput dc2Goods = 4;</code>
   * @return The dc2Goods.
   */
  com.didiyun.bill.v1.CheckDc2PriceInput getDc2Goods();
  /**
   * <code>.didi.cloud.bill.v1.CheckDc2PriceInput dc2Goods = 4;</code>
   */
  com.didiyun.bill.v1.CheckDc2PriceInputOrBuilder getDc2GoodsOrBuilder();
}
