// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill/v1/bill.proto

package com.didiyun.bill.v1;

public interface CheckEbsPriceInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.bill.v1.CheckEbsPriceInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *ebs数量
   * </pre>
   *
   * <code>int32 count = 1;</code>
   * @return The count.
   */
  int getCount();

  /**
   * <pre>
   *购买包月时长，单位为月，不传或传0表示后付费
   * </pre>
   *
   * <code>int32 payPeriod = 2;</code>
   * @return The payPeriod.
   */
  int getPayPeriod();

  /**
   * <pre>
   *ebs大小
   * </pre>
   *
   * <code>int32 size = 3;</code>
   * @return The size.
   */
  int getSize();

  /**
   * <pre>
   *EBS类型
   * </pre>
   *
   * <code>string diskType = 4;</code>
   * @return The diskType.
   */
  java.lang.String getDiskType();
  /**
   * <pre>
   *EBS类型
   * </pre>
   *
   * <code>string diskType = 4;</code>
   * @return The bytes for diskType.
   */
  com.google.protobuf.ByteString
      getDiskTypeBytes();

  /**
   * <pre>
   *当为更改规格时，传此ebsUuid
   * </pre>
   *
   * <code>string ebsUuid = 5;</code>
   * @return The ebsUuid.
   */
  java.lang.String getEbsUuid();
  /**
   * <pre>
   *当为更改规格时，传此ebsUuid
   * </pre>
   *
   * <code>string ebsUuid = 5;</code>
   * @return The bytes for ebsUuid.
   */
  com.google.protobuf.ByteString
      getEbsUuidBytes();
}
