// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill/v1/bill.proto

package com.didiyun.bill.v1;

public interface ContinueListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.bill.v1.ContinueListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   * @return The header.
   */
  com.didiyun.base.v1.Header getHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  com.didiyun.base.v1.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   *列表开始位置
   * </pre>
   *
   * <code>int32 start = 2;</code>
   * @return The start.
   */
  int getStart();

  /**
   * <pre>
   *取出数量
   * </pre>
   *
   * <code>int32 limit = 3;</code>
   * @return The limit.
   */
  int getLimit();

  /**
   * <pre>
   *过滤条件
   * </pre>
   *
   * <code>.didi.cloud.bill.v1.ContinueListCondition condition = 5;</code>
   * @return Whether the condition field is set.
   */
  boolean hasCondition();
  /**
   * <pre>
   *过滤条件
   * </pre>
   *
   * <code>.didi.cloud.bill.v1.ContinueListCondition condition = 5;</code>
   * @return The condition.
   */
  com.didiyun.bill.v1.ContinueListCondition getCondition();
  /**
   * <pre>
   *过滤条件
   * </pre>
   *
   * <code>.didi.cloud.bill.v1.ContinueListCondition condition = 5;</code>
   */
  com.didiyun.bill.v1.ContinueListConditionOrBuilder getConditionOrBuilder();
}
