// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill/v1/bill.proto

package com.didiyun.bill.v1;

public interface Dc2ChargeInfoAndSpecOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.bill.v1.Dc2ChargeInfoAndSpec)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *资源Uuid
   * </pre>
   *
   * <code>string resourceUuid = 1;</code>
   * @return The resourceUuid.
   */
  java.lang.String getResourceUuid();
  /**
   * <pre>
   *资源Uuid
   * </pre>
   *
   * <code>string resourceUuid = 1;</code>
   * @return The bytes for resourceUuid.
   */
  com.google.protobuf.ByteString
      getResourceUuidBytes();

  /**
   * <code>.didi.cloud.bill.v1.ChargeInfo charge = 2;</code>
   * @return Whether the charge field is set.
   */
  boolean hasCharge();
  /**
   * <code>.didi.cloud.bill.v1.ChargeInfo charge = 2;</code>
   * @return The charge.
   */
  com.didiyun.bill.v1.ChargeInfo getCharge();
  /**
   * <code>.didi.cloud.bill.v1.ChargeInfo charge = 2;</code>
   */
  com.didiyun.bill.v1.ChargeInfoOrBuilder getChargeOrBuilder();

  /**
   * <code>.didi.cloud.bill.v1.Dc2Spec spec = 3;</code>
   * @return Whether the spec field is set.
   */
  boolean hasSpec();
  /**
   * <code>.didi.cloud.bill.v1.Dc2Spec spec = 3;</code>
   * @return The spec.
   */
  com.didiyun.bill.v1.Dc2Spec getSpec();
  /**
   * <code>.didi.cloud.bill.v1.Dc2Spec spec = 3;</code>
   */
  com.didiyun.bill.v1.Dc2SpecOrBuilder getSpecOrBuilder();
}
