// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/vpc.proto

package com.didiyun.compute.v1;

public interface CheckSubnetCidrOverlapRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.CheckSubnetCidrOverlapRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   * @return The header.
   */
  com.didiyun.base.v1.Header getHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  com.didiyun.base.v1.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   *要检查的vpc
   * </pre>
   *
   * <code>string vpcUuid = 2;</code>
   * @return The vpcUuid.
   */
  java.lang.String getVpcUuid();
  /**
   * <pre>
   *要检查的vpc
   * </pre>
   *
   * <code>string vpcUuid = 2;</code>
   * @return The bytes for vpcUuid.
   */
  com.google.protobuf.ByteString
      getVpcUuidBytes();

  /**
   * <pre>
   *要检查的网段
   * </pre>
   *
   * <code>string cidr = 3;</code>
   * @return The cidr.
   */
  java.lang.String getCidr();
  /**
   * <pre>
   *要检查的网段
   * </pre>
   *
   * <code>string cidr = 3;</code>
   * @return The bytes for cidr.
   */
  com.google.protobuf.ByteString
      getCidrBytes();
}
