// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/common.proto

package com.didiyun.compute.v1;

public interface CportInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.CportInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *CPort唯一标识
   * </pre>
   *
   * <code>string cportUuid = 1;</code>
   * @return The cportUuid.
   */
  java.lang.String getCportUuid();
  /**
   * <pre>
   *CPort唯一标识
   * </pre>
   *
   * <code>string cportUuid = 1;</code>
   * @return The bytes for cportUuid.
   */
  com.google.protobuf.ByteString
      getCportUuidBytes();

  /**
   * <pre>
   *Ip
   * </pre>
   *
   * <code>string ip = 2;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <pre>
   *Ip
   * </pre>
   *
   * <code>string ip = 2;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <pre>
   *容器Id
   * </pre>
   *
   * <code>string containerId = 3;</code>
   * @return The containerId.
   */
  java.lang.String getContainerId();
  /**
   * <pre>
   *容器Id
   * </pre>
   *
   * <code>string containerId = 3;</code>
   * @return The bytes for containerId.
   */
  com.google.protobuf.ByteString
      getContainerIdBytes();

  /**
   * <pre>
   *vm的MAC地址
   * </pre>
   *
   * <code>string mac = 4;</code>
   * @return The mac.
   */
  java.lang.String getMac();
  /**
   * <pre>
   *vm的MAC地址
   * </pre>
   *
   * <code>string mac = 4;</code>
   * @return The bytes for mac.
   */
  com.google.protobuf.ByteString
      getMacBytes();

  /**
   * <pre>
   *掩码
   * </pre>
   *
   * <code>string netmask = 5;</code>
   * @return The netmask.
   */
  java.lang.String getNetmask();
  /**
   * <pre>
   *掩码
   * </pre>
   *
   * <code>string netmask = 5;</code>
   * @return The bytes for netmask.
   */
  com.google.protobuf.ByteString
      getNetmaskBytes();

  /**
   * <pre>
   *PodName
   * </pre>
   *
   * <code>string podName = 6;</code>
   * @return The podName.
   */
  java.lang.String getPodName();
  /**
   * <pre>
   *PodName
   * </pre>
   *
   * <code>string podName = 6;</code>
   * @return The bytes for podName.
   */
  com.google.protobuf.ByteString
      getPodNameBytes();

  /**
   * <pre>
   *PodNs
   * </pre>
   *
   * <code>string podNs = 7;</code>
   * @return The podNs.
   */
  java.lang.String getPodNs();
  /**
   * <pre>
   *PodNs
   * </pre>
   *
   * <code>string podNs = 7;</code>
   * @return The bytes for podNs.
   */
  com.google.protobuf.ByteString
      getPodNsBytes();

  /**
   * <pre>
   *VmNic唯一标识
   * </pre>
   *
   * <code>string vmNicUuid = 8;</code>
   * @return The vmNicUuid.
   */
  java.lang.String getVmNicUuid();
  /**
   * <pre>
   *VmNic唯一标识
   * </pre>
   *
   * <code>string vmNicUuid = 8;</code>
   * @return The bytes for vmNicUuid.
   */
  com.google.protobuf.ByteString
      getVmNicUuidBytes();

  /**
   * <pre>
   *网关
   * </pre>
   *
   * <code>string gateway = 9;</code>
   * @return The gateway.
   */
  java.lang.String getGateway();
  /**
   * <pre>
   *网关
   * </pre>
   *
   * <code>string gateway = 9;</code>
   * @return The bytes for gateway.
   */
  com.google.protobuf.ByteString
      getGatewayBytes();

  /**
   * <pre>
   *创建时间
   * </pre>
   *
   * <code>int64 createTime = 10;</code>
   * @return The createTime.
   */
  long getCreateTime();

  /**
   * <pre>
   *更新时间
   * </pre>
   *
   * <code>int64 updateTime = 11;</code>
   * @return The updateTime.
   */
  long getUpdateTime();

  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
   * @return Whether the job field is set.
   */
  boolean hasJob();
  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
   * @return The job.
   */
  com.didiyun.base.v1.JobInfo getJob();
  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
   */
  com.didiyun.base.v1.JobInfoOrBuilder getJobOrBuilder();
}
