// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/snap.proto

package com.didiyun.compute.v1;

public interface CreateSnapshotRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.CreateSnapshotRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   * @return The header.
   */
  com.didiyun.base.v1.Header getHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  com.didiyun.base.v1.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   *根据DC2创建快照，与ebsUuid参数二选一
   * </pre>
   *
   * <code>string dc2Uuid = 2;</code>
   * @return The dc2Uuid.
   */
  java.lang.String getDc2Uuid();
  /**
   * <pre>
   *根据DC2创建快照，与ebsUuid参数二选一
   * </pre>
   *
   * <code>string dc2Uuid = 2;</code>
   * @return The bytes for dc2Uuid.
   */
  com.google.protobuf.ByteString
      getDc2UuidBytes();

  /**
   * <pre>
   *根据EBS创建快照，与dc2Uuid参数二选一
   * </pre>
   *
   * <code>string ebsUuid = 3;</code>
   * @return The ebsUuid.
   */
  java.lang.String getEbsUuid();
  /**
   * <pre>
   *根据EBS创建快照，与dc2Uuid参数二选一
   * </pre>
   *
   * <code>string ebsUuid = 3;</code>
   * @return The bytes for ebsUuid.
   */
  com.google.protobuf.ByteString
      getEbsUuidBytes();

  /**
   * <pre>
   *快照名称
   * </pre>
   *
   * <code>string snapName = 4;</code>
   * @return The snapName.
   */
  java.lang.String getSnapName();
  /**
   * <pre>
   *快照名称
   * </pre>
   *
   * <code>string snapName = 4;</code>
   * @return The bytes for snapName.
   */
  com.google.protobuf.ByteString
      getSnapNameBytes();
}
