// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/common.proto

package com.didiyun.compute.v1;

public interface Dc2InfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.Dc2Info)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *dc2UUID
   * </pre>
   *
   * <code>string dc2Uuid = 1;</code>
   * @return The dc2Uuid.
   */
  java.lang.String getDc2Uuid();
  /**
   * <pre>
   *dc2UUID
   * </pre>
   *
   * <code>string dc2Uuid = 1;</code>
   * @return The bytes for dc2Uuid.
   */
  com.google.protobuf.ByteString
      getDc2UuidBytes();

  /**
   * <pre>
   *dc2名称
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *dc2名称
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *dc2创建时间
   * </pre>
   *
   * <code>int64 createTime = 3;</code>
   * @return The createTime.
   */
  long getCreateTime();

  /**
   * <pre>
   *dc2更改时间
   * </pre>
   *
   * <code>int64 updateTime = 4;</code>
   * @return The updateTime.
   */
  long getUpdateTime();

  /**
   * <pre>
   *dc2的内网Ip
   * </pre>
   *
   * <code>string ip = 5;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <pre>
   *dc2的内网Ip
   * </pre>
   *
   * <code>string ip = 5;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <pre>
   *dc2的状态
   * </pre>
   *
   * <code>string status = 6;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   *dc2的状态
   * </pre>
   *
   * <code>string status = 6;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <pre>
   *操作系统类型
   * </pre>
   *
   * <code>string osType = 7;</code>
   * @return The osType.
   */
  java.lang.String getOsType();
  /**
   * <pre>
   *操作系统类型
   * </pre>
   *
   * <code>string osType = 7;</code>
   * @return The bytes for osType.
   */
  com.google.protobuf.ByteString
      getOsTypeBytes();

  /**
   * <pre>
   *系统平台
   * </pre>
   *
   * <code>string platform = 8;</code>
   * @return The platform.
   */
  java.lang.String getPlatform();
  /**
   * <pre>
   *系统平台
   * </pre>
   *
   * <code>string platform = 8;</code>
   * @return The bytes for platform.
   */
  com.google.protobuf.ByteString
      getPlatformBytes();

  /**
   * <pre>
   *镜像uuid
   * </pre>
   *
   * <code>string imgUuid = 9;</code>
   * @return The imgUuid.
   */
  java.lang.String getImgUuid();
  /**
   * <pre>
   *镜像uuid
   * </pre>
   *
   * <code>string imgUuid = 9;</code>
   * @return The bytes for imgUuid.
   */
  com.google.protobuf.ByteString
      getImgUuidBytes();

  /**
   * <pre>
   *镜像ID
   * </pre>
   *
   * <code>string imgId = 10;</code>
   * @return The imgId.
   */
  java.lang.String getImgId();
  /**
   * <pre>
   *镜像ID
   * </pre>
   *
   * <code>string imgId = 10;</code>
   * @return The bytes for imgId.
   */
  com.google.protobuf.ByteString
      getImgIdBytes();

  /**
   * <pre>
   *标签
   * </pre>
   *
   * <code>repeated string tags = 11;</code>
   * @return A list containing the tags.
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <pre>
   *标签
   * </pre>
   *
   * <code>repeated string tags = 11;</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <pre>
   *标签
   * </pre>
   *
   * <code>repeated string tags = 11;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  java.lang.String getTags(int index);
  /**
   * <pre>
   *标签
   * </pre>
   *
   * <code>repeated string tags = 11;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);

  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
   * @return Whether the job field is set.
   */
  boolean hasJob();
  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
   * @return The job.
   */
  com.didiyun.base.v1.JobInfo getJob();
  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
   */
  com.didiyun.base.v1.JobInfoOrBuilder getJobOrBuilder();

  /**
   * <pre>
   *dc2的eip绑定信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.EipInfo eip = 13;</code>
   * @return Whether the eip field is set.
   */
  boolean hasEip();
  /**
   * <pre>
   *dc2的eip绑定信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.EipInfo eip = 13;</code>
   * @return The eip.
   */
  com.didiyun.compute.v1.EipInfo getEip();
  /**
   * <pre>
   *dc2的eip绑定信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.EipInfo eip = 13;</code>
   */
  com.didiyun.compute.v1.EipInfoOrBuilder getEipOrBuilder();

  /**
   * <pre>
   *dc2的ebs绑定信息
   * </pre>
   *
   * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
   */
  java.util.List<com.didiyun.compute.v1.EbsInfo> 
      getEbsList();
  /**
   * <pre>
   *dc2的ebs绑定信息
   * </pre>
   *
   * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
   */
  com.didiyun.compute.v1.EbsInfo getEbs(int index);
  /**
   * <pre>
   *dc2的ebs绑定信息
   * </pre>
   *
   * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
   */
  int getEbsCount();
  /**
   * <pre>
   *dc2的ebs绑定信息
   * </pre>
   *
   * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
   */
  java.util.List<? extends com.didiyun.compute.v1.EbsInfoOrBuilder> 
      getEbsOrBuilderList();
  /**
   * <pre>
   *dc2的ebs绑定信息
   * </pre>
   *
   * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
   */
  com.didiyun.compute.v1.EbsInfoOrBuilder getEbsOrBuilder(
      int index);

  /**
   * <pre>
   *region信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.RegionInfo region = 15;</code>
   * @return Whether the region field is set.
   */
  boolean hasRegion();
  /**
   * <pre>
   *region信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.RegionInfo region = 15;</code>
   * @return The region.
   */
  com.didiyun.base.v1.RegionInfo getRegion();
  /**
   * <pre>
   *region信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.RegionInfo region = 15;</code>
   */
  com.didiyun.base.v1.RegionInfoOrBuilder getRegionOrBuilder();
}
