// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/common.proto

package com.didiyun.compute.v1;

/**
 * Protobuf type {@code didi.cloud.compute.v1.Dc2Info}
 */
public  final class Dc2Info extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:didi.cloud.compute.v1.Dc2Info)
    Dc2InfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Dc2Info.newBuilder() to construct.
  private Dc2Info(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Dc2Info() {
    dc2Uuid_ = "";
    name_ = "";
    ip_ = "";
    status_ = "";
    osType_ = "";
    platform_ = "";
    imgUuid_ = "";
    imgId_ = "";
    tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    ebs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Dc2Info();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Dc2Info(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            dc2Uuid_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {

            createTime_ = input.readInt64();
            break;
          }
          case 32: {

            updateTime_ = input.readInt64();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            ip_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            osType_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            platform_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            imgUuid_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            imgId_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              tags_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            tags_.add(s);
            break;
          }
          case 98: {
            com.didiyun.base.v1.JobInfo.Builder subBuilder = null;
            if (job_ != null) {
              subBuilder = job_.toBuilder();
            }
            job_ = input.readMessage(com.didiyun.base.v1.JobInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(job_);
              job_ = subBuilder.buildPartial();
            }

            break;
          }
          case 106: {
            com.didiyun.compute.v1.EipInfo.Builder subBuilder = null;
            if (eip_ != null) {
              subBuilder = eip_.toBuilder();
            }
            eip_ = input.readMessage(com.didiyun.compute.v1.EipInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(eip_);
              eip_ = subBuilder.buildPartial();
            }

            break;
          }
          case 114: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              ebs_ = new java.util.ArrayList<com.didiyun.compute.v1.EbsInfo>();
              mutable_bitField0_ |= 0x00000002;
            }
            ebs_.add(
                input.readMessage(com.didiyun.compute.v1.EbsInfo.parser(), extensionRegistry));
            break;
          }
          case 122: {
            com.didiyun.base.v1.RegionInfo.Builder subBuilder = null;
            if (region_ != null) {
              subBuilder = region_.toBuilder();
            }
            region_ = input.readMessage(com.didiyun.base.v1.RegionInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(region_);
              region_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        tags_ = tags_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        ebs_ = java.util.Collections.unmodifiableList(ebs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.didiyun.compute.v1.CommonOuterClass.internal_static_didi_cloud_compute_v1_Dc2Info_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.didiyun.compute.v1.CommonOuterClass.internal_static_didi_cloud_compute_v1_Dc2Info_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.didiyun.compute.v1.Dc2Info.class, com.didiyun.compute.v1.Dc2Info.Builder.class);
  }

  public static final int DC2UUID_FIELD_NUMBER = 1;
  private volatile java.lang.Object dc2Uuid_;
  /**
   * <pre>
   *dc2UUID
   * </pre>
   *
   * <code>string dc2Uuid = 1;</code>
   * @return The dc2Uuid.
   */
  public java.lang.String getDc2Uuid() {
    java.lang.Object ref = dc2Uuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dc2Uuid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *dc2UUID
   * </pre>
   *
   * <code>string dc2Uuid = 1;</code>
   * @return The bytes for dc2Uuid.
   */
  public com.google.protobuf.ByteString
      getDc2UuidBytes() {
    java.lang.Object ref = dc2Uuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dc2Uuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   *dc2名称
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *dc2名称
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATETIME_FIELD_NUMBER = 3;
  private long createTime_;
  /**
   * <pre>
   *dc2创建时间
   * </pre>
   *
   * <code>int64 createTime = 3;</code>
   * @return The createTime.
   */
  public long getCreateTime() {
    return createTime_;
  }

  public static final int UPDATETIME_FIELD_NUMBER = 4;
  private long updateTime_;
  /**
   * <pre>
   *dc2更改时间
   * </pre>
   *
   * <code>int64 updateTime = 4;</code>
   * @return The updateTime.
   */
  public long getUpdateTime() {
    return updateTime_;
  }

  public static final int IP_FIELD_NUMBER = 5;
  private volatile java.lang.Object ip_;
  /**
   * <pre>
   *dc2的内网Ip
   * </pre>
   *
   * <code>string ip = 5;</code>
   * @return The ip.
   */
  public java.lang.String getIp() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ip_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *dc2的内网Ip
   * </pre>
   *
   * <code>string ip = 5;</code>
   * @return The bytes for ip.
   */
  public com.google.protobuf.ByteString
      getIpBytes() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ip_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 6;
  private volatile java.lang.Object status_;
  /**
   * <pre>
   *dc2的状态
   * </pre>
   *
   * <code>string status = 6;</code>
   * @return The status.
   */
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *dc2的状态
   * </pre>
   *
   * <code>string status = 6;</code>
   * @return The bytes for status.
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OSTYPE_FIELD_NUMBER = 7;
  private volatile java.lang.Object osType_;
  /**
   * <pre>
   *操作系统类型
   * </pre>
   *
   * <code>string osType = 7;</code>
   * @return The osType.
   */
  public java.lang.String getOsType() {
    java.lang.Object ref = osType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      osType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *操作系统类型
   * </pre>
   *
   * <code>string osType = 7;</code>
   * @return The bytes for osType.
   */
  public com.google.protobuf.ByteString
      getOsTypeBytes() {
    java.lang.Object ref = osType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      osType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLATFORM_FIELD_NUMBER = 8;
  private volatile java.lang.Object platform_;
  /**
   * <pre>
   *系统平台
   * </pre>
   *
   * <code>string platform = 8;</code>
   * @return The platform.
   */
  public java.lang.String getPlatform() {
    java.lang.Object ref = platform_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      platform_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *系统平台
   * </pre>
   *
   * <code>string platform = 8;</code>
   * @return The bytes for platform.
   */
  public com.google.protobuf.ByteString
      getPlatformBytes() {
    java.lang.Object ref = platform_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      platform_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMGUUID_FIELD_NUMBER = 9;
  private volatile java.lang.Object imgUuid_;
  /**
   * <pre>
   *镜像uuid
   * </pre>
   *
   * <code>string imgUuid = 9;</code>
   * @return The imgUuid.
   */
  public java.lang.String getImgUuid() {
    java.lang.Object ref = imgUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      imgUuid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *镜像uuid
   * </pre>
   *
   * <code>string imgUuid = 9;</code>
   * @return The bytes for imgUuid.
   */
  public com.google.protobuf.ByteString
      getImgUuidBytes() {
    java.lang.Object ref = imgUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      imgUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMGID_FIELD_NUMBER = 10;
  private volatile java.lang.Object imgId_;
  /**
   * <pre>
   *镜像ID
   * </pre>
   *
   * <code>string imgId = 10;</code>
   * @return The imgId.
   */
  public java.lang.String getImgId() {
    java.lang.Object ref = imgId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      imgId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *镜像ID
   * </pre>
   *
   * <code>string imgId = 10;</code>
   * @return The bytes for imgId.
   */
  public com.google.protobuf.ByteString
      getImgIdBytes() {
    java.lang.Object ref = imgId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      imgId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAGS_FIELD_NUMBER = 11;
  private com.google.protobuf.LazyStringList tags_;
  /**
   * <pre>
   *标签
   * </pre>
   *
   * <code>repeated string tags = 11;</code>
   * @return A list containing the tags.
   */
  public com.google.protobuf.ProtocolStringList
      getTagsList() {
    return tags_;
  }
  /**
   * <pre>
   *标签
   * </pre>
   *
   * <code>repeated string tags = 11;</code>
   * @return The count of tags.
   */
  public int getTagsCount() {
    return tags_.size();
  }
  /**
   * <pre>
   *标签
   * </pre>
   *
   * <code>repeated string tags = 11;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  public java.lang.String getTags(int index) {
    return tags_.get(index);
  }
  /**
   * <pre>
   *标签
   * </pre>
   *
   * <code>repeated string tags = 11;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  public com.google.protobuf.ByteString
      getTagsBytes(int index) {
    return tags_.getByteString(index);
  }

  public static final int JOB_FIELD_NUMBER = 12;
  private com.didiyun.base.v1.JobInfo job_;
  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
   * @return Whether the job field is set.
   */
  public boolean hasJob() {
    return job_ != null;
  }
  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
   * @return The job.
   */
  public com.didiyun.base.v1.JobInfo getJob() {
    return job_ == null ? com.didiyun.base.v1.JobInfo.getDefaultInstance() : job_;
  }
  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
   */
  public com.didiyun.base.v1.JobInfoOrBuilder getJobOrBuilder() {
    return getJob();
  }

  public static final int EIP_FIELD_NUMBER = 13;
  private com.didiyun.compute.v1.EipInfo eip_;
  /**
   * <pre>
   *dc2的eip绑定信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.EipInfo eip = 13;</code>
   * @return Whether the eip field is set.
   */
  public boolean hasEip() {
    return eip_ != null;
  }
  /**
   * <pre>
   *dc2的eip绑定信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.EipInfo eip = 13;</code>
   * @return The eip.
   */
  public com.didiyun.compute.v1.EipInfo getEip() {
    return eip_ == null ? com.didiyun.compute.v1.EipInfo.getDefaultInstance() : eip_;
  }
  /**
   * <pre>
   *dc2的eip绑定信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.EipInfo eip = 13;</code>
   */
  public com.didiyun.compute.v1.EipInfoOrBuilder getEipOrBuilder() {
    return getEip();
  }

  public static final int EBS_FIELD_NUMBER = 14;
  private java.util.List<com.didiyun.compute.v1.EbsInfo> ebs_;
  /**
   * <pre>
   *dc2的ebs绑定信息
   * </pre>
   *
   * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
   */
  public java.util.List<com.didiyun.compute.v1.EbsInfo> getEbsList() {
    return ebs_;
  }
  /**
   * <pre>
   *dc2的ebs绑定信息
   * </pre>
   *
   * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
   */
  public java.util.List<? extends com.didiyun.compute.v1.EbsInfoOrBuilder> 
      getEbsOrBuilderList() {
    return ebs_;
  }
  /**
   * <pre>
   *dc2的ebs绑定信息
   * </pre>
   *
   * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
   */
  public int getEbsCount() {
    return ebs_.size();
  }
  /**
   * <pre>
   *dc2的ebs绑定信息
   * </pre>
   *
   * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
   */
  public com.didiyun.compute.v1.EbsInfo getEbs(int index) {
    return ebs_.get(index);
  }
  /**
   * <pre>
   *dc2的ebs绑定信息
   * </pre>
   *
   * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
   */
  public com.didiyun.compute.v1.EbsInfoOrBuilder getEbsOrBuilder(
      int index) {
    return ebs_.get(index);
  }

  public static final int REGION_FIELD_NUMBER = 15;
  private com.didiyun.base.v1.RegionInfo region_;
  /**
   * <pre>
   *region信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.RegionInfo region = 15;</code>
   * @return Whether the region field is set.
   */
  public boolean hasRegion() {
    return region_ != null;
  }
  /**
   * <pre>
   *region信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.RegionInfo region = 15;</code>
   * @return The region.
   */
  public com.didiyun.base.v1.RegionInfo getRegion() {
    return region_ == null ? com.didiyun.base.v1.RegionInfo.getDefaultInstance() : region_;
  }
  /**
   * <pre>
   *region信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.RegionInfo region = 15;</code>
   */
  public com.didiyun.base.v1.RegionInfoOrBuilder getRegionOrBuilder() {
    return getRegion();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDc2UuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dc2Uuid_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (createTime_ != 0L) {
      output.writeInt64(3, createTime_);
    }
    if (updateTime_ != 0L) {
      output.writeInt64(4, updateTime_);
    }
    if (!getIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, ip_);
    }
    if (!getStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, status_);
    }
    if (!getOsTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, osType_);
    }
    if (!getPlatformBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, platform_);
    }
    if (!getImgUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, imgUuid_);
    }
    if (!getImgIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, imgId_);
    }
    for (int i = 0; i < tags_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, tags_.getRaw(i));
    }
    if (job_ != null) {
      output.writeMessage(12, getJob());
    }
    if (eip_ != null) {
      output.writeMessage(13, getEip());
    }
    for (int i = 0; i < ebs_.size(); i++) {
      output.writeMessage(14, ebs_.get(i));
    }
    if (region_ != null) {
      output.writeMessage(15, getRegion());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDc2UuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dc2Uuid_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (createTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, createTime_);
    }
    if (updateTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, updateTime_);
    }
    if (!getIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, ip_);
    }
    if (!getStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, status_);
    }
    if (!getOsTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, osType_);
    }
    if (!getPlatformBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, platform_);
    }
    if (!getImgUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, imgUuid_);
    }
    if (!getImgIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, imgId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < tags_.size(); i++) {
        dataSize += computeStringSizeNoTag(tags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTagsList().size();
    }
    if (job_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, getJob());
    }
    if (eip_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, getEip());
    }
    for (int i = 0; i < ebs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, ebs_.get(i));
    }
    if (region_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, getRegion());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.didiyun.compute.v1.Dc2Info)) {
      return super.equals(obj);
    }
    com.didiyun.compute.v1.Dc2Info other = (com.didiyun.compute.v1.Dc2Info) obj;

    if (!getDc2Uuid()
        .equals(other.getDc2Uuid())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (getCreateTime()
        != other.getCreateTime()) return false;
    if (getUpdateTime()
        != other.getUpdateTime()) return false;
    if (!getIp()
        .equals(other.getIp())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (!getOsType()
        .equals(other.getOsType())) return false;
    if (!getPlatform()
        .equals(other.getPlatform())) return false;
    if (!getImgUuid()
        .equals(other.getImgUuid())) return false;
    if (!getImgId()
        .equals(other.getImgId())) return false;
    if (!getTagsList()
        .equals(other.getTagsList())) return false;
    if (hasJob() != other.hasJob()) return false;
    if (hasJob()) {
      if (!getJob()
          .equals(other.getJob())) return false;
    }
    if (hasEip() != other.hasEip()) return false;
    if (hasEip()) {
      if (!getEip()
          .equals(other.getEip())) return false;
    }
    if (!getEbsList()
        .equals(other.getEbsList())) return false;
    if (hasRegion() != other.hasRegion()) return false;
    if (hasRegion()) {
      if (!getRegion()
          .equals(other.getRegion())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DC2UUID_FIELD_NUMBER;
    hash = (53 * hash) + getDc2Uuid().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreateTime());
    hash = (37 * hash) + UPDATETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUpdateTime());
    hash = (37 * hash) + IP_FIELD_NUMBER;
    hash = (53 * hash) + getIp().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + OSTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getOsType().hashCode();
    hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
    hash = (53 * hash) + getPlatform().hashCode();
    hash = (37 * hash) + IMGUUID_FIELD_NUMBER;
    hash = (53 * hash) + getImgUuid().hashCode();
    hash = (37 * hash) + IMGID_FIELD_NUMBER;
    hash = (53 * hash) + getImgId().hashCode();
    if (getTagsCount() > 0) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getTagsList().hashCode();
    }
    if (hasJob()) {
      hash = (37 * hash) + JOB_FIELD_NUMBER;
      hash = (53 * hash) + getJob().hashCode();
    }
    if (hasEip()) {
      hash = (37 * hash) + EIP_FIELD_NUMBER;
      hash = (53 * hash) + getEip().hashCode();
    }
    if (getEbsCount() > 0) {
      hash = (37 * hash) + EBS_FIELD_NUMBER;
      hash = (53 * hash) + getEbsList().hashCode();
    }
    if (hasRegion()) {
      hash = (37 * hash) + REGION_FIELD_NUMBER;
      hash = (53 * hash) + getRegion().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.didiyun.compute.v1.Dc2Info parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.compute.v1.Dc2Info parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.compute.v1.Dc2Info parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.compute.v1.Dc2Info parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.compute.v1.Dc2Info parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.compute.v1.Dc2Info parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.compute.v1.Dc2Info parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.didiyun.compute.v1.Dc2Info parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.didiyun.compute.v1.Dc2Info parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.didiyun.compute.v1.Dc2Info parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.didiyun.compute.v1.Dc2Info parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.didiyun.compute.v1.Dc2Info parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.didiyun.compute.v1.Dc2Info prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code didi.cloud.compute.v1.Dc2Info}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:didi.cloud.compute.v1.Dc2Info)
      com.didiyun.compute.v1.Dc2InfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.didiyun.compute.v1.CommonOuterClass.internal_static_didi_cloud_compute_v1_Dc2Info_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.didiyun.compute.v1.CommonOuterClass.internal_static_didi_cloud_compute_v1_Dc2Info_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.didiyun.compute.v1.Dc2Info.class, com.didiyun.compute.v1.Dc2Info.Builder.class);
    }

    // Construct using com.didiyun.compute.v1.Dc2Info.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEbsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      dc2Uuid_ = "";

      name_ = "";

      createTime_ = 0L;

      updateTime_ = 0L;

      ip_ = "";

      status_ = "";

      osType_ = "";

      platform_ = "";

      imgUuid_ = "";

      imgId_ = "";

      tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (jobBuilder_ == null) {
        job_ = null;
      } else {
        job_ = null;
        jobBuilder_ = null;
      }
      if (eipBuilder_ == null) {
        eip_ = null;
      } else {
        eip_ = null;
        eipBuilder_ = null;
      }
      if (ebsBuilder_ == null) {
        ebs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        ebsBuilder_.clear();
      }
      if (regionBuilder_ == null) {
        region_ = null;
      } else {
        region_ = null;
        regionBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.didiyun.compute.v1.CommonOuterClass.internal_static_didi_cloud_compute_v1_Dc2Info_descriptor;
    }

    @java.lang.Override
    public com.didiyun.compute.v1.Dc2Info getDefaultInstanceForType() {
      return com.didiyun.compute.v1.Dc2Info.getDefaultInstance();
    }

    @java.lang.Override
    public com.didiyun.compute.v1.Dc2Info build() {
      com.didiyun.compute.v1.Dc2Info result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.didiyun.compute.v1.Dc2Info buildPartial() {
      com.didiyun.compute.v1.Dc2Info result = new com.didiyun.compute.v1.Dc2Info(this);
      int from_bitField0_ = bitField0_;
      result.dc2Uuid_ = dc2Uuid_;
      result.name_ = name_;
      result.createTime_ = createTime_;
      result.updateTime_ = updateTime_;
      result.ip_ = ip_;
      result.status_ = status_;
      result.osType_ = osType_;
      result.platform_ = platform_;
      result.imgUuid_ = imgUuid_;
      result.imgId_ = imgId_;
      if (((bitField0_ & 0x00000001) != 0)) {
        tags_ = tags_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.tags_ = tags_;
      if (jobBuilder_ == null) {
        result.job_ = job_;
      } else {
        result.job_ = jobBuilder_.build();
      }
      if (eipBuilder_ == null) {
        result.eip_ = eip_;
      } else {
        result.eip_ = eipBuilder_.build();
      }
      if (ebsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          ebs_ = java.util.Collections.unmodifiableList(ebs_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.ebs_ = ebs_;
      } else {
        result.ebs_ = ebsBuilder_.build();
      }
      if (regionBuilder_ == null) {
        result.region_ = region_;
      } else {
        result.region_ = regionBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.didiyun.compute.v1.Dc2Info) {
        return mergeFrom((com.didiyun.compute.v1.Dc2Info)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.didiyun.compute.v1.Dc2Info other) {
      if (other == com.didiyun.compute.v1.Dc2Info.getDefaultInstance()) return this;
      if (!other.getDc2Uuid().isEmpty()) {
        dc2Uuid_ = other.dc2Uuid_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getCreateTime() != 0L) {
        setCreateTime(other.getCreateTime());
      }
      if (other.getUpdateTime() != 0L) {
        setUpdateTime(other.getUpdateTime());
      }
      if (!other.getIp().isEmpty()) {
        ip_ = other.ip_;
        onChanged();
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      if (!other.getOsType().isEmpty()) {
        osType_ = other.osType_;
        onChanged();
      }
      if (!other.getPlatform().isEmpty()) {
        platform_ = other.platform_;
        onChanged();
      }
      if (!other.getImgUuid().isEmpty()) {
        imgUuid_ = other.imgUuid_;
        onChanged();
      }
      if (!other.getImgId().isEmpty()) {
        imgId_ = other.imgId_;
        onChanged();
      }
      if (!other.tags_.isEmpty()) {
        if (tags_.isEmpty()) {
          tags_ = other.tags_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTagsIsMutable();
          tags_.addAll(other.tags_);
        }
        onChanged();
      }
      if (other.hasJob()) {
        mergeJob(other.getJob());
      }
      if (other.hasEip()) {
        mergeEip(other.getEip());
      }
      if (ebsBuilder_ == null) {
        if (!other.ebs_.isEmpty()) {
          if (ebs_.isEmpty()) {
            ebs_ = other.ebs_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureEbsIsMutable();
            ebs_.addAll(other.ebs_);
          }
          onChanged();
        }
      } else {
        if (!other.ebs_.isEmpty()) {
          if (ebsBuilder_.isEmpty()) {
            ebsBuilder_.dispose();
            ebsBuilder_ = null;
            ebs_ = other.ebs_;
            bitField0_ = (bitField0_ & ~0x00000002);
            ebsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEbsFieldBuilder() : null;
          } else {
            ebsBuilder_.addAllMessages(other.ebs_);
          }
        }
      }
      if (other.hasRegion()) {
        mergeRegion(other.getRegion());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.didiyun.compute.v1.Dc2Info parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.didiyun.compute.v1.Dc2Info) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object dc2Uuid_ = "";
    /**
     * <pre>
     *dc2UUID
     * </pre>
     *
     * <code>string dc2Uuid = 1;</code>
     * @return The dc2Uuid.
     */
    public java.lang.String getDc2Uuid() {
      java.lang.Object ref = dc2Uuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dc2Uuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *dc2UUID
     * </pre>
     *
     * <code>string dc2Uuid = 1;</code>
     * @return The bytes for dc2Uuid.
     */
    public com.google.protobuf.ByteString
        getDc2UuidBytes() {
      java.lang.Object ref = dc2Uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dc2Uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *dc2UUID
     * </pre>
     *
     * <code>string dc2Uuid = 1;</code>
     * @param value The dc2Uuid to set.
     * @return This builder for chaining.
     */
    public Builder setDc2Uuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dc2Uuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *dc2UUID
     * </pre>
     *
     * <code>string dc2Uuid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDc2Uuid() {
      
      dc2Uuid_ = getDefaultInstance().getDc2Uuid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *dc2UUID
     * </pre>
     *
     * <code>string dc2Uuid = 1;</code>
     * @param value The bytes for dc2Uuid to set.
     * @return This builder for chaining.
     */
    public Builder setDc2UuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dc2Uuid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     *dc2名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *dc2名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *dc2名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *dc2名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *dc2名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private long createTime_ ;
    /**
     * <pre>
     *dc2创建时间
     * </pre>
     *
     * <code>int64 createTime = 3;</code>
     * @return The createTime.
     */
    public long getCreateTime() {
      return createTime_;
    }
    /**
     * <pre>
     *dc2创建时间
     * </pre>
     *
     * <code>int64 createTime = 3;</code>
     * @param value The createTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreateTime(long value) {
      
      createTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *dc2创建时间
     * </pre>
     *
     * <code>int64 createTime = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreateTime() {
      
      createTime_ = 0L;
      onChanged();
      return this;
    }

    private long updateTime_ ;
    /**
     * <pre>
     *dc2更改时间
     * </pre>
     *
     * <code>int64 updateTime = 4;</code>
     * @return The updateTime.
     */
    public long getUpdateTime() {
      return updateTime_;
    }
    /**
     * <pre>
     *dc2更改时间
     * </pre>
     *
     * <code>int64 updateTime = 4;</code>
     * @param value The updateTime to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateTime(long value) {
      
      updateTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *dc2更改时间
     * </pre>
     *
     * <code>int64 updateTime = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdateTime() {
      
      updateTime_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object ip_ = "";
    /**
     * <pre>
     *dc2的内网Ip
     * </pre>
     *
     * <code>string ip = 5;</code>
     * @return The ip.
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *dc2的内网Ip
     * </pre>
     *
     * <code>string ip = 5;</code>
     * @return The bytes for ip.
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *dc2的内网Ip
     * </pre>
     *
     * <code>string ip = 5;</code>
     * @param value The ip to set.
     * @return This builder for chaining.
     */
    public Builder setIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ip_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *dc2的内网Ip
     * </pre>
     *
     * <code>string ip = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIp() {
      
      ip_ = getDefaultInstance().getIp();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *dc2的内网Ip
     * </pre>
     *
     * <code>string ip = 5;</code>
     * @param value The bytes for ip to set.
     * @return This builder for chaining.
     */
    public Builder setIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ip_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <pre>
     *dc2的状态
     * </pre>
     *
     * <code>string status = 6;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *dc2的状态
     * </pre>
     *
     * <code>string status = 6;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *dc2的状态
     * </pre>
     *
     * <code>string status = 6;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *dc2的状态
     * </pre>
     *
     * <code>string status = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *dc2的状态
     * </pre>
     *
     * <code>string status = 6;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      status_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object osType_ = "";
    /**
     * <pre>
     *操作系统类型
     * </pre>
     *
     * <code>string osType = 7;</code>
     * @return The osType.
     */
    public java.lang.String getOsType() {
      java.lang.Object ref = osType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        osType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *操作系统类型
     * </pre>
     *
     * <code>string osType = 7;</code>
     * @return The bytes for osType.
     */
    public com.google.protobuf.ByteString
        getOsTypeBytes() {
      java.lang.Object ref = osType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        osType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *操作系统类型
     * </pre>
     *
     * <code>string osType = 7;</code>
     * @param value The osType to set.
     * @return This builder for chaining.
     */
    public Builder setOsType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      osType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *操作系统类型
     * </pre>
     *
     * <code>string osType = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearOsType() {
      
      osType_ = getDefaultInstance().getOsType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *操作系统类型
     * </pre>
     *
     * <code>string osType = 7;</code>
     * @param value The bytes for osType to set.
     * @return This builder for chaining.
     */
    public Builder setOsTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      osType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object platform_ = "";
    /**
     * <pre>
     *系统平台
     * </pre>
     *
     * <code>string platform = 8;</code>
     * @return The platform.
     */
    public java.lang.String getPlatform() {
      java.lang.Object ref = platform_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        platform_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *系统平台
     * </pre>
     *
     * <code>string platform = 8;</code>
     * @return The bytes for platform.
     */
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      java.lang.Object ref = platform_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *系统平台
     * </pre>
     *
     * <code>string platform = 8;</code>
     * @param value The platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatform(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      platform_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *系统平台
     * </pre>
     *
     * <code>string platform = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatform() {
      
      platform_ = getDefaultInstance().getPlatform();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *系统平台
     * </pre>
     *
     * <code>string platform = 8;</code>
     * @param value The bytes for platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      platform_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object imgUuid_ = "";
    /**
     * <pre>
     *镜像uuid
     * </pre>
     *
     * <code>string imgUuid = 9;</code>
     * @return The imgUuid.
     */
    public java.lang.String getImgUuid() {
      java.lang.Object ref = imgUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imgUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *镜像uuid
     * </pre>
     *
     * <code>string imgUuid = 9;</code>
     * @return The bytes for imgUuid.
     */
    public com.google.protobuf.ByteString
        getImgUuidBytes() {
      java.lang.Object ref = imgUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imgUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *镜像uuid
     * </pre>
     *
     * <code>string imgUuid = 9;</code>
     * @param value The imgUuid to set.
     * @return This builder for chaining.
     */
    public Builder setImgUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imgUuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *镜像uuid
     * </pre>
     *
     * <code>string imgUuid = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearImgUuid() {
      
      imgUuid_ = getDefaultInstance().getImgUuid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *镜像uuid
     * </pre>
     *
     * <code>string imgUuid = 9;</code>
     * @param value The bytes for imgUuid to set.
     * @return This builder for chaining.
     */
    public Builder setImgUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      imgUuid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object imgId_ = "";
    /**
     * <pre>
     *镜像ID
     * </pre>
     *
     * <code>string imgId = 10;</code>
     * @return The imgId.
     */
    public java.lang.String getImgId() {
      java.lang.Object ref = imgId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imgId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *镜像ID
     * </pre>
     *
     * <code>string imgId = 10;</code>
     * @return The bytes for imgId.
     */
    public com.google.protobuf.ByteString
        getImgIdBytes() {
      java.lang.Object ref = imgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *镜像ID
     * </pre>
     *
     * <code>string imgId = 10;</code>
     * @param value The imgId to set.
     * @return This builder for chaining.
     */
    public Builder setImgId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imgId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *镜像ID
     * </pre>
     *
     * <code>string imgId = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearImgId() {
      
      imgId_ = getDefaultInstance().getImgId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *镜像ID
     * </pre>
     *
     * <code>string imgId = 10;</code>
     * @param value The bytes for imgId to set.
     * @return This builder for chaining.
     */
    public Builder setImgIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      imgId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTagsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     *标签
     * </pre>
     *
     * <code>repeated string tags = 11;</code>
     * @return A list containing the tags.
     */
    public com.google.protobuf.ProtocolStringList
        getTagsList() {
      return tags_.getUnmodifiableView();
    }
    /**
     * <pre>
     *标签
     * </pre>
     *
     * <code>repeated string tags = 11;</code>
     * @return The count of tags.
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <pre>
     *标签
     * </pre>
     *
     * <code>repeated string tags = 11;</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    public java.lang.String getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <pre>
     *标签
     * </pre>
     *
     * <code>repeated string tags = 11;</code>
     * @param index The index of the value to return.
     * @return The bytes of the tags at the given index.
     */
    public com.google.protobuf.ByteString
        getTagsBytes(int index) {
      return tags_.getByteString(index);
    }
    /**
     * <pre>
     *标签
     * </pre>
     *
     * <code>repeated string tags = 11;</code>
     * @param index The index to set the value at.
     * @param value The tags to set.
     * @return This builder for chaining.
     */
    public Builder setTags(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
      tags_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *标签
     * </pre>
     *
     * <code>repeated string tags = 11;</code>
     * @param value The tags to add.
     * @return This builder for chaining.
     */
    public Builder addTags(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
      tags_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *标签
     * </pre>
     *
     * <code>repeated string tags = 11;</code>
     * @param values The tags to add.
     * @return This builder for chaining.
     */
    public Builder addAllTags(
        java.lang.Iterable<java.lang.String> values) {
      ensureTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tags_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *标签
     * </pre>
     *
     * <code>repeated string tags = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearTags() {
      tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *标签
     * </pre>
     *
     * <code>repeated string tags = 11;</code>
     * @param value The bytes of the tags to add.
     * @return This builder for chaining.
     */
    public Builder addTagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureTagsIsMutable();
      tags_.add(value);
      onChanged();
      return this;
    }

    private com.didiyun.base.v1.JobInfo job_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.didiyun.base.v1.JobInfo, com.didiyun.base.v1.JobInfo.Builder, com.didiyun.base.v1.JobInfoOrBuilder> jobBuilder_;
    /**
     * <pre>
     *任务
     * </pre>
     *
     * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
     * @return Whether the job field is set.
     */
    public boolean hasJob() {
      return jobBuilder_ != null || job_ != null;
    }
    /**
     * <pre>
     *任务
     * </pre>
     *
     * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
     * @return The job.
     */
    public com.didiyun.base.v1.JobInfo getJob() {
      if (jobBuilder_ == null) {
        return job_ == null ? com.didiyun.base.v1.JobInfo.getDefaultInstance() : job_;
      } else {
        return jobBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *任务
     * </pre>
     *
     * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
     */
    public Builder setJob(com.didiyun.base.v1.JobInfo value) {
      if (jobBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        job_ = value;
        onChanged();
      } else {
        jobBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *任务
     * </pre>
     *
     * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
     */
    public Builder setJob(
        com.didiyun.base.v1.JobInfo.Builder builderForValue) {
      if (jobBuilder_ == null) {
        job_ = builderForValue.build();
        onChanged();
      } else {
        jobBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *任务
     * </pre>
     *
     * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
     */
    public Builder mergeJob(com.didiyun.base.v1.JobInfo value) {
      if (jobBuilder_ == null) {
        if (job_ != null) {
          job_ =
            com.didiyun.base.v1.JobInfo.newBuilder(job_).mergeFrom(value).buildPartial();
        } else {
          job_ = value;
        }
        onChanged();
      } else {
        jobBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *任务
     * </pre>
     *
     * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
     */
    public Builder clearJob() {
      if (jobBuilder_ == null) {
        job_ = null;
        onChanged();
      } else {
        job_ = null;
        jobBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *任务
     * </pre>
     *
     * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
     */
    public com.didiyun.base.v1.JobInfo.Builder getJobBuilder() {
      
      onChanged();
      return getJobFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *任务
     * </pre>
     *
     * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
     */
    public com.didiyun.base.v1.JobInfoOrBuilder getJobOrBuilder() {
      if (jobBuilder_ != null) {
        return jobBuilder_.getMessageOrBuilder();
      } else {
        return job_ == null ?
            com.didiyun.base.v1.JobInfo.getDefaultInstance() : job_;
      }
    }
    /**
     * <pre>
     *任务
     * </pre>
     *
     * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.didiyun.base.v1.JobInfo, com.didiyun.base.v1.JobInfo.Builder, com.didiyun.base.v1.JobInfoOrBuilder> 
        getJobFieldBuilder() {
      if (jobBuilder_ == null) {
        jobBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.didiyun.base.v1.JobInfo, com.didiyun.base.v1.JobInfo.Builder, com.didiyun.base.v1.JobInfoOrBuilder>(
                getJob(),
                getParentForChildren(),
                isClean());
        job_ = null;
      }
      return jobBuilder_;
    }

    private com.didiyun.compute.v1.EipInfo eip_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.didiyun.compute.v1.EipInfo, com.didiyun.compute.v1.EipInfo.Builder, com.didiyun.compute.v1.EipInfoOrBuilder> eipBuilder_;
    /**
     * <pre>
     *dc2的eip绑定信息
     * </pre>
     *
     * <code>.didi.cloud.compute.v1.EipInfo eip = 13;</code>
     * @return Whether the eip field is set.
     */
    public boolean hasEip() {
      return eipBuilder_ != null || eip_ != null;
    }
    /**
     * <pre>
     *dc2的eip绑定信息
     * </pre>
     *
     * <code>.didi.cloud.compute.v1.EipInfo eip = 13;</code>
     * @return The eip.
     */
    public com.didiyun.compute.v1.EipInfo getEip() {
      if (eipBuilder_ == null) {
        return eip_ == null ? com.didiyun.compute.v1.EipInfo.getDefaultInstance() : eip_;
      } else {
        return eipBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *dc2的eip绑定信息
     * </pre>
     *
     * <code>.didi.cloud.compute.v1.EipInfo eip = 13;</code>
     */
    public Builder setEip(com.didiyun.compute.v1.EipInfo value) {
      if (eipBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        eip_ = value;
        onChanged();
      } else {
        eipBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *dc2的eip绑定信息
     * </pre>
     *
     * <code>.didi.cloud.compute.v1.EipInfo eip = 13;</code>
     */
    public Builder setEip(
        com.didiyun.compute.v1.EipInfo.Builder builderForValue) {
      if (eipBuilder_ == null) {
        eip_ = builderForValue.build();
        onChanged();
      } else {
        eipBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *dc2的eip绑定信息
     * </pre>
     *
     * <code>.didi.cloud.compute.v1.EipInfo eip = 13;</code>
     */
    public Builder mergeEip(com.didiyun.compute.v1.EipInfo value) {
      if (eipBuilder_ == null) {
        if (eip_ != null) {
          eip_ =
            com.didiyun.compute.v1.EipInfo.newBuilder(eip_).mergeFrom(value).buildPartial();
        } else {
          eip_ = value;
        }
        onChanged();
      } else {
        eipBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *dc2的eip绑定信息
     * </pre>
     *
     * <code>.didi.cloud.compute.v1.EipInfo eip = 13;</code>
     */
    public Builder clearEip() {
      if (eipBuilder_ == null) {
        eip_ = null;
        onChanged();
      } else {
        eip_ = null;
        eipBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *dc2的eip绑定信息
     * </pre>
     *
     * <code>.didi.cloud.compute.v1.EipInfo eip = 13;</code>
     */
    public com.didiyun.compute.v1.EipInfo.Builder getEipBuilder() {
      
      onChanged();
      return getEipFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *dc2的eip绑定信息
     * </pre>
     *
     * <code>.didi.cloud.compute.v1.EipInfo eip = 13;</code>
     */
    public com.didiyun.compute.v1.EipInfoOrBuilder getEipOrBuilder() {
      if (eipBuilder_ != null) {
        return eipBuilder_.getMessageOrBuilder();
      } else {
        return eip_ == null ?
            com.didiyun.compute.v1.EipInfo.getDefaultInstance() : eip_;
      }
    }
    /**
     * <pre>
     *dc2的eip绑定信息
     * </pre>
     *
     * <code>.didi.cloud.compute.v1.EipInfo eip = 13;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.didiyun.compute.v1.EipInfo, com.didiyun.compute.v1.EipInfo.Builder, com.didiyun.compute.v1.EipInfoOrBuilder> 
        getEipFieldBuilder() {
      if (eipBuilder_ == null) {
        eipBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.didiyun.compute.v1.EipInfo, com.didiyun.compute.v1.EipInfo.Builder, com.didiyun.compute.v1.EipInfoOrBuilder>(
                getEip(),
                getParentForChildren(),
                isClean());
        eip_ = null;
      }
      return eipBuilder_;
    }

    private java.util.List<com.didiyun.compute.v1.EbsInfo> ebs_ =
      java.util.Collections.emptyList();
    private void ensureEbsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        ebs_ = new java.util.ArrayList<com.didiyun.compute.v1.EbsInfo>(ebs_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.didiyun.compute.v1.EbsInfo, com.didiyun.compute.v1.EbsInfo.Builder, com.didiyun.compute.v1.EbsInfoOrBuilder> ebsBuilder_;

    /**
     * <pre>
     *dc2的ebs绑定信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
     */
    public java.util.List<com.didiyun.compute.v1.EbsInfo> getEbsList() {
      if (ebsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ebs_);
      } else {
        return ebsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *dc2的ebs绑定信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
     */
    public int getEbsCount() {
      if (ebsBuilder_ == null) {
        return ebs_.size();
      } else {
        return ebsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *dc2的ebs绑定信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
     */
    public com.didiyun.compute.v1.EbsInfo getEbs(int index) {
      if (ebsBuilder_ == null) {
        return ebs_.get(index);
      } else {
        return ebsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *dc2的ebs绑定信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
     */
    public Builder setEbs(
        int index, com.didiyun.compute.v1.EbsInfo value) {
      if (ebsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEbsIsMutable();
        ebs_.set(index, value);
        onChanged();
      } else {
        ebsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *dc2的ebs绑定信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
     */
    public Builder setEbs(
        int index, com.didiyun.compute.v1.EbsInfo.Builder builderForValue) {
      if (ebsBuilder_ == null) {
        ensureEbsIsMutable();
        ebs_.set(index, builderForValue.build());
        onChanged();
      } else {
        ebsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *dc2的ebs绑定信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
     */
    public Builder addEbs(com.didiyun.compute.v1.EbsInfo value) {
      if (ebsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEbsIsMutable();
        ebs_.add(value);
        onChanged();
      } else {
        ebsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *dc2的ebs绑定信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
     */
    public Builder addEbs(
        int index, com.didiyun.compute.v1.EbsInfo value) {
      if (ebsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEbsIsMutable();
        ebs_.add(index, value);
        onChanged();
      } else {
        ebsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *dc2的ebs绑定信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
     */
    public Builder addEbs(
        com.didiyun.compute.v1.EbsInfo.Builder builderForValue) {
      if (ebsBuilder_ == null) {
        ensureEbsIsMutable();
        ebs_.add(builderForValue.build());
        onChanged();
      } else {
        ebsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *dc2的ebs绑定信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
     */
    public Builder addEbs(
        int index, com.didiyun.compute.v1.EbsInfo.Builder builderForValue) {
      if (ebsBuilder_ == null) {
        ensureEbsIsMutable();
        ebs_.add(index, builderForValue.build());
        onChanged();
      } else {
        ebsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *dc2的ebs绑定信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
     */
    public Builder addAllEbs(
        java.lang.Iterable<? extends com.didiyun.compute.v1.EbsInfo> values) {
      if (ebsBuilder_ == null) {
        ensureEbsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ebs_);
        onChanged();
      } else {
        ebsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *dc2的ebs绑定信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
     */
    public Builder clearEbs() {
      if (ebsBuilder_ == null) {
        ebs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        ebsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *dc2的ebs绑定信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
     */
    public Builder removeEbs(int index) {
      if (ebsBuilder_ == null) {
        ensureEbsIsMutable();
        ebs_.remove(index);
        onChanged();
      } else {
        ebsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *dc2的ebs绑定信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
     */
    public com.didiyun.compute.v1.EbsInfo.Builder getEbsBuilder(
        int index) {
      return getEbsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *dc2的ebs绑定信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
     */
    public com.didiyun.compute.v1.EbsInfoOrBuilder getEbsOrBuilder(
        int index) {
      if (ebsBuilder_ == null) {
        return ebs_.get(index);  } else {
        return ebsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *dc2的ebs绑定信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
     */
    public java.util.List<? extends com.didiyun.compute.v1.EbsInfoOrBuilder> 
         getEbsOrBuilderList() {
      if (ebsBuilder_ != null) {
        return ebsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ebs_);
      }
    }
    /**
     * <pre>
     *dc2的ebs绑定信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
     */
    public com.didiyun.compute.v1.EbsInfo.Builder addEbsBuilder() {
      return getEbsFieldBuilder().addBuilder(
          com.didiyun.compute.v1.EbsInfo.getDefaultInstance());
    }
    /**
     * <pre>
     *dc2的ebs绑定信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
     */
    public com.didiyun.compute.v1.EbsInfo.Builder addEbsBuilder(
        int index) {
      return getEbsFieldBuilder().addBuilder(
          index, com.didiyun.compute.v1.EbsInfo.getDefaultInstance());
    }
    /**
     * <pre>
     *dc2的ebs绑定信息
     * </pre>
     *
     * <code>repeated .didi.cloud.compute.v1.EbsInfo ebs = 14;</code>
     */
    public java.util.List<com.didiyun.compute.v1.EbsInfo.Builder> 
         getEbsBuilderList() {
      return getEbsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.didiyun.compute.v1.EbsInfo, com.didiyun.compute.v1.EbsInfo.Builder, com.didiyun.compute.v1.EbsInfoOrBuilder> 
        getEbsFieldBuilder() {
      if (ebsBuilder_ == null) {
        ebsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.didiyun.compute.v1.EbsInfo, com.didiyun.compute.v1.EbsInfo.Builder, com.didiyun.compute.v1.EbsInfoOrBuilder>(
                ebs_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        ebs_ = null;
      }
      return ebsBuilder_;
    }

    private com.didiyun.base.v1.RegionInfo region_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.didiyun.base.v1.RegionInfo, com.didiyun.base.v1.RegionInfo.Builder, com.didiyun.base.v1.RegionInfoOrBuilder> regionBuilder_;
    /**
     * <pre>
     *region信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.RegionInfo region = 15;</code>
     * @return Whether the region field is set.
     */
    public boolean hasRegion() {
      return regionBuilder_ != null || region_ != null;
    }
    /**
     * <pre>
     *region信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.RegionInfo region = 15;</code>
     * @return The region.
     */
    public com.didiyun.base.v1.RegionInfo getRegion() {
      if (regionBuilder_ == null) {
        return region_ == null ? com.didiyun.base.v1.RegionInfo.getDefaultInstance() : region_;
      } else {
        return regionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *region信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.RegionInfo region = 15;</code>
     */
    public Builder setRegion(com.didiyun.base.v1.RegionInfo value) {
      if (regionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        region_ = value;
        onChanged();
      } else {
        regionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *region信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.RegionInfo region = 15;</code>
     */
    public Builder setRegion(
        com.didiyun.base.v1.RegionInfo.Builder builderForValue) {
      if (regionBuilder_ == null) {
        region_ = builderForValue.build();
        onChanged();
      } else {
        regionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *region信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.RegionInfo region = 15;</code>
     */
    public Builder mergeRegion(com.didiyun.base.v1.RegionInfo value) {
      if (regionBuilder_ == null) {
        if (region_ != null) {
          region_ =
            com.didiyun.base.v1.RegionInfo.newBuilder(region_).mergeFrom(value).buildPartial();
        } else {
          region_ = value;
        }
        onChanged();
      } else {
        regionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *region信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.RegionInfo region = 15;</code>
     */
    public Builder clearRegion() {
      if (regionBuilder_ == null) {
        region_ = null;
        onChanged();
      } else {
        region_ = null;
        regionBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *region信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.RegionInfo region = 15;</code>
     */
    public com.didiyun.base.v1.RegionInfo.Builder getRegionBuilder() {
      
      onChanged();
      return getRegionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *region信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.RegionInfo region = 15;</code>
     */
    public com.didiyun.base.v1.RegionInfoOrBuilder getRegionOrBuilder() {
      if (regionBuilder_ != null) {
        return regionBuilder_.getMessageOrBuilder();
      } else {
        return region_ == null ?
            com.didiyun.base.v1.RegionInfo.getDefaultInstance() : region_;
      }
    }
    /**
     * <pre>
     *region信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.RegionInfo region = 15;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.didiyun.base.v1.RegionInfo, com.didiyun.base.v1.RegionInfo.Builder, com.didiyun.base.v1.RegionInfoOrBuilder> 
        getRegionFieldBuilder() {
      if (regionBuilder_ == null) {
        regionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.didiyun.base.v1.RegionInfo, com.didiyun.base.v1.RegionInfo.Builder, com.didiyun.base.v1.RegionInfoOrBuilder>(
                getRegion(),
                getParentForChildren(),
                isClean());
        region_ = null;
      }
      return regionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:didi.cloud.compute.v1.Dc2Info)
  }

  // @@protoc_insertion_point(class_scope:didi.cloud.compute.v1.Dc2Info)
  private static final com.didiyun.compute.v1.Dc2Info DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.didiyun.compute.v1.Dc2Info();
  }

  public static com.didiyun.compute.v1.Dc2Info getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Dc2Info>
      PARSER = new com.google.protobuf.AbstractParser<Dc2Info>() {
    @java.lang.Override
    public Dc2Info parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Dc2Info(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Dc2Info> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Dc2Info> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.didiyun.compute.v1.Dc2Info getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

