// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/common.proto

package com.didiyun.compute.v1;

public interface EbsInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.EbsInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string ebsUuid = 2;</code>
   * @return The ebsUuid.
   */
  java.lang.String getEbsUuid();
  /**
   * <code>string ebsUuid = 2;</code>
   * @return The bytes for ebsUuid.
   */
  com.google.protobuf.ByteString
      getEbsUuidBytes();

  /**
   * <pre>
   *种类（SSD、NVMe）
   * </pre>
   *
   * <code>string type = 3;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   *种类（SSD、NVMe）
   * </pre>
   *
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <pre>
   *属性（数据盘、根盘）
   * </pre>
   *
   * <code>string attr = 4;</code>
   * @return The attr.
   */
  java.lang.String getAttr();
  /**
   * <pre>
   *属性（数据盘、根盘）
   * </pre>
   *
   * <code>string attr = 4;</code>
   * @return The bytes for attr.
   */
  com.google.protobuf.ByteString
      getAttrBytes();

  /**
   * <pre>
   *标签
   * </pre>
   *
   * <code>repeated string ebsTags = 5;</code>
   * @return A list containing the ebsTags.
   */
  java.util.List<java.lang.String>
      getEbsTagsList();
  /**
   * <pre>
   *标签
   * </pre>
   *
   * <code>repeated string ebsTags = 5;</code>
   * @return The count of ebsTags.
   */
  int getEbsTagsCount();
  /**
   * <pre>
   *标签
   * </pre>
   *
   * <code>repeated string ebsTags = 5;</code>
   * @param index The index of the element to return.
   * @return The ebsTags at the given index.
   */
  java.lang.String getEbsTags(int index);
  /**
   * <pre>
   *标签
   * </pre>
   *
   * <code>repeated string ebsTags = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the ebsTags at the given index.
   */
  com.google.protobuf.ByteString
      getEbsTagsBytes(int index);

  /**
   * <pre>
   *region信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.RegionAndZoneInfo region = 6;</code>
   * @return Whether the region field is set.
   */
  boolean hasRegion();
  /**
   * <pre>
   *region信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.RegionAndZoneInfo region = 6;</code>
   * @return The region.
   */
  com.didiyun.base.v1.RegionAndZoneInfo getRegion();
  /**
   * <pre>
   *region信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.RegionAndZoneInfo region = 6;</code>
   */
  com.didiyun.base.v1.RegionAndZoneInfoOrBuilder getRegionOrBuilder();

  /**
   * <pre>
   *设备名（盘符）
   * </pre>
   *
   * <code>string deviceName = 7;</code>
   * @return The deviceName.
   */
  java.lang.String getDeviceName();
  /**
   * <pre>
   *设备名（盘符）
   * </pre>
   *
   * <code>string deviceName = 7;</code>
   * @return The bytes for deviceName.
   */
  com.google.protobuf.ByteString
      getDeviceNameBytes();

  /**
   * <pre>
   *创建时间
   * </pre>
   *
   * <code>int64 createTime = 8;</code>
   * @return The createTime.
   */
  long getCreateTime();

  /**
   * <pre>
   *更新时间
   * </pre>
   *
   * <code>int64 updateTime = 9;</code>
   * @return The updateTime.
   */
  long getUpdateTime();

  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 10;</code>
   * @return Whether the job field is set.
   */
  boolean hasJob();
  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 10;</code>
   * @return The job.
   */
  com.didiyun.base.v1.JobInfo getJob();
  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 10;</code>
   */
  com.didiyun.base.v1.JobInfoOrBuilder getJobOrBuilder();

  /**
   * <pre>
   *与EBS绑定的DC2信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.Dc2Info dc2 = 11;</code>
   * @return Whether the dc2 field is set.
   */
  boolean hasDc2();
  /**
   * <pre>
   *与EBS绑定的DC2信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.Dc2Info dc2 = 11;</code>
   * @return The dc2.
   */
  com.didiyun.compute.v1.Dc2Info getDc2();
  /**
   * <pre>
   *与EBS绑定的DC2信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.Dc2Info dc2 = 11;</code>
   */
  com.didiyun.compute.v1.Dc2InfoOrBuilder getDc2OrBuilder();
}
