// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/common.proto

package com.didiyun.compute.v1;

/**
 * Protobuf type {@code didi.cloud.compute.v1.EbsInfo}
 */
public  final class EbsInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:didi.cloud.compute.v1.EbsInfo)
    EbsInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EbsInfo.newBuilder() to construct.
  private EbsInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EbsInfo() {
    name_ = "";
    ebsUuid_ = "";
    type_ = "";
    attr_ = "";
    ebsTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    deviceName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EbsInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EbsInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            ebsUuid_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            attr_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              ebsTags_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            ebsTags_.add(s);
            break;
          }
          case 50: {
            com.didiyun.base.v1.RegionAndZoneInfo.Builder subBuilder = null;
            if (region_ != null) {
              subBuilder = region_.toBuilder();
            }
            region_ = input.readMessage(com.didiyun.base.v1.RegionAndZoneInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(region_);
              region_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceName_ = s;
            break;
          }
          case 64: {

            createTime_ = input.readInt64();
            break;
          }
          case 72: {

            updateTime_ = input.readInt64();
            break;
          }
          case 82: {
            com.didiyun.base.v1.JobInfo.Builder subBuilder = null;
            if (job_ != null) {
              subBuilder = job_.toBuilder();
            }
            job_ = input.readMessage(com.didiyun.base.v1.JobInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(job_);
              job_ = subBuilder.buildPartial();
            }

            break;
          }
          case 90: {
            com.didiyun.compute.v1.Dc2Info.Builder subBuilder = null;
            if (dc2_ != null) {
              subBuilder = dc2_.toBuilder();
            }
            dc2_ = input.readMessage(com.didiyun.compute.v1.Dc2Info.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dc2_);
              dc2_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        ebsTags_ = ebsTags_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.didiyun.compute.v1.CommonOuterClass.internal_static_didi_cloud_compute_v1_EbsInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.didiyun.compute.v1.CommonOuterClass.internal_static_didi_cloud_compute_v1_EbsInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.didiyun.compute.v1.EbsInfo.class, com.didiyun.compute.v1.EbsInfo.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EBSUUID_FIELD_NUMBER = 2;
  private volatile java.lang.Object ebsUuid_;
  /**
   * <code>string ebsUuid = 2;</code>
   * @return The ebsUuid.
   */
  public java.lang.String getEbsUuid() {
    java.lang.Object ref = ebsUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ebsUuid_ = s;
      return s;
    }
  }
  /**
   * <code>string ebsUuid = 2;</code>
   * @return The bytes for ebsUuid.
   */
  public com.google.protobuf.ByteString
      getEbsUuidBytes() {
    java.lang.Object ref = ebsUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ebsUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  private volatile java.lang.Object type_;
  /**
   * <pre>
   *种类（SSD、NVMe）
   * </pre>
   *
   * <code>string type = 3;</code>
   * @return The type.
   */
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *种类（SSD、NVMe）
   * </pre>
   *
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTR_FIELD_NUMBER = 4;
  private volatile java.lang.Object attr_;
  /**
   * <pre>
   *属性（数据盘、根盘）
   * </pre>
   *
   * <code>string attr = 4;</code>
   * @return The attr.
   */
  public java.lang.String getAttr() {
    java.lang.Object ref = attr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      attr_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *属性（数据盘、根盘）
   * </pre>
   *
   * <code>string attr = 4;</code>
   * @return The bytes for attr.
   */
  public com.google.protobuf.ByteString
      getAttrBytes() {
    java.lang.Object ref = attr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      attr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EBSTAGS_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList ebsTags_;
  /**
   * <pre>
   *标签
   * </pre>
   *
   * <code>repeated string ebsTags = 5;</code>
   * @return A list containing the ebsTags.
   */
  public com.google.protobuf.ProtocolStringList
      getEbsTagsList() {
    return ebsTags_;
  }
  /**
   * <pre>
   *标签
   * </pre>
   *
   * <code>repeated string ebsTags = 5;</code>
   * @return The count of ebsTags.
   */
  public int getEbsTagsCount() {
    return ebsTags_.size();
  }
  /**
   * <pre>
   *标签
   * </pre>
   *
   * <code>repeated string ebsTags = 5;</code>
   * @param index The index of the element to return.
   * @return The ebsTags at the given index.
   */
  public java.lang.String getEbsTags(int index) {
    return ebsTags_.get(index);
  }
  /**
   * <pre>
   *标签
   * </pre>
   *
   * <code>repeated string ebsTags = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the ebsTags at the given index.
   */
  public com.google.protobuf.ByteString
      getEbsTagsBytes(int index) {
    return ebsTags_.getByteString(index);
  }

  public static final int REGION_FIELD_NUMBER = 6;
  private com.didiyun.base.v1.RegionAndZoneInfo region_;
  /**
   * <pre>
   *region信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.RegionAndZoneInfo region = 6;</code>
   * @return Whether the region field is set.
   */
  public boolean hasRegion() {
    return region_ != null;
  }
  /**
   * <pre>
   *region信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.RegionAndZoneInfo region = 6;</code>
   * @return The region.
   */
  public com.didiyun.base.v1.RegionAndZoneInfo getRegion() {
    return region_ == null ? com.didiyun.base.v1.RegionAndZoneInfo.getDefaultInstance() : region_;
  }
  /**
   * <pre>
   *region信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.RegionAndZoneInfo region = 6;</code>
   */
  public com.didiyun.base.v1.RegionAndZoneInfoOrBuilder getRegionOrBuilder() {
    return getRegion();
  }

  public static final int DEVICENAME_FIELD_NUMBER = 7;
  private volatile java.lang.Object deviceName_;
  /**
   * <pre>
   *设备名（盘符）
   * </pre>
   *
   * <code>string deviceName = 7;</code>
   * @return The deviceName.
   */
  public java.lang.String getDeviceName() {
    java.lang.Object ref = deviceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *设备名（盘符）
   * </pre>
   *
   * <code>string deviceName = 7;</code>
   * @return The bytes for deviceName.
   */
  public com.google.protobuf.ByteString
      getDeviceNameBytes() {
    java.lang.Object ref = deviceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATETIME_FIELD_NUMBER = 8;
  private long createTime_;
  /**
   * <pre>
   *创建时间
   * </pre>
   *
   * <code>int64 createTime = 8;</code>
   * @return The createTime.
   */
  public long getCreateTime() {
    return createTime_;
  }

  public static final int UPDATETIME_FIELD_NUMBER = 9;
  private long updateTime_;
  /**
   * <pre>
   *更新时间
   * </pre>
   *
   * <code>int64 updateTime = 9;</code>
   * @return The updateTime.
   */
  public long getUpdateTime() {
    return updateTime_;
  }

  public static final int JOB_FIELD_NUMBER = 10;
  private com.didiyun.base.v1.JobInfo job_;
  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 10;</code>
   * @return Whether the job field is set.
   */
  public boolean hasJob() {
    return job_ != null;
  }
  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 10;</code>
   * @return The job.
   */
  public com.didiyun.base.v1.JobInfo getJob() {
    return job_ == null ? com.didiyun.base.v1.JobInfo.getDefaultInstance() : job_;
  }
  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 10;</code>
   */
  public com.didiyun.base.v1.JobInfoOrBuilder getJobOrBuilder() {
    return getJob();
  }

  public static final int DC2_FIELD_NUMBER = 11;
  private com.didiyun.compute.v1.Dc2Info dc2_;
  /**
   * <pre>
   *与EBS绑定的DC2信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.Dc2Info dc2 = 11;</code>
   * @return Whether the dc2 field is set.
   */
  public boolean hasDc2() {
    return dc2_ != null;
  }
  /**
   * <pre>
   *与EBS绑定的DC2信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.Dc2Info dc2 = 11;</code>
   * @return The dc2.
   */
  public com.didiyun.compute.v1.Dc2Info getDc2() {
    return dc2_ == null ? com.didiyun.compute.v1.Dc2Info.getDefaultInstance() : dc2_;
  }
  /**
   * <pre>
   *与EBS绑定的DC2信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.Dc2Info dc2 = 11;</code>
   */
  public com.didiyun.compute.v1.Dc2InfoOrBuilder getDc2OrBuilder() {
    return getDc2();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getEbsUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ebsUuid_);
    }
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
    }
    if (!getAttrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, attr_);
    }
    for (int i = 0; i < ebsTags_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, ebsTags_.getRaw(i));
    }
    if (region_ != null) {
      output.writeMessage(6, getRegion());
    }
    if (!getDeviceNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, deviceName_);
    }
    if (createTime_ != 0L) {
      output.writeInt64(8, createTime_);
    }
    if (updateTime_ != 0L) {
      output.writeInt64(9, updateTime_);
    }
    if (job_ != null) {
      output.writeMessage(10, getJob());
    }
    if (dc2_ != null) {
      output.writeMessage(11, getDc2());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getEbsUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ebsUuid_);
    }
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
    }
    if (!getAttrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, attr_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < ebsTags_.size(); i++) {
        dataSize += computeStringSizeNoTag(ebsTags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getEbsTagsList().size();
    }
    if (region_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getRegion());
    }
    if (!getDeviceNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, deviceName_);
    }
    if (createTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, createTime_);
    }
    if (updateTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, updateTime_);
    }
    if (job_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getJob());
    }
    if (dc2_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getDc2());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.didiyun.compute.v1.EbsInfo)) {
      return super.equals(obj);
    }
    com.didiyun.compute.v1.EbsInfo other = (com.didiyun.compute.v1.EbsInfo) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getEbsUuid()
        .equals(other.getEbsUuid())) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (!getAttr()
        .equals(other.getAttr())) return false;
    if (!getEbsTagsList()
        .equals(other.getEbsTagsList())) return false;
    if (hasRegion() != other.hasRegion()) return false;
    if (hasRegion()) {
      if (!getRegion()
          .equals(other.getRegion())) return false;
    }
    if (!getDeviceName()
        .equals(other.getDeviceName())) return false;
    if (getCreateTime()
        != other.getCreateTime()) return false;
    if (getUpdateTime()
        != other.getUpdateTime()) return false;
    if (hasJob() != other.hasJob()) return false;
    if (hasJob()) {
      if (!getJob()
          .equals(other.getJob())) return false;
    }
    if (hasDc2() != other.hasDc2()) return false;
    if (hasDc2()) {
      if (!getDc2()
          .equals(other.getDc2())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + EBSUUID_FIELD_NUMBER;
    hash = (53 * hash) + getEbsUuid().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + ATTR_FIELD_NUMBER;
    hash = (53 * hash) + getAttr().hashCode();
    if (getEbsTagsCount() > 0) {
      hash = (37 * hash) + EBSTAGS_FIELD_NUMBER;
      hash = (53 * hash) + getEbsTagsList().hashCode();
    }
    if (hasRegion()) {
      hash = (37 * hash) + REGION_FIELD_NUMBER;
      hash = (53 * hash) + getRegion().hashCode();
    }
    hash = (37 * hash) + DEVICENAME_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceName().hashCode();
    hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreateTime());
    hash = (37 * hash) + UPDATETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUpdateTime());
    if (hasJob()) {
      hash = (37 * hash) + JOB_FIELD_NUMBER;
      hash = (53 * hash) + getJob().hashCode();
    }
    if (hasDc2()) {
      hash = (37 * hash) + DC2_FIELD_NUMBER;
      hash = (53 * hash) + getDc2().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.didiyun.compute.v1.EbsInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.compute.v1.EbsInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.compute.v1.EbsInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.compute.v1.EbsInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.compute.v1.EbsInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.compute.v1.EbsInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.compute.v1.EbsInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.didiyun.compute.v1.EbsInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.didiyun.compute.v1.EbsInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.didiyun.compute.v1.EbsInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.didiyun.compute.v1.EbsInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.didiyun.compute.v1.EbsInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.didiyun.compute.v1.EbsInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code didi.cloud.compute.v1.EbsInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:didi.cloud.compute.v1.EbsInfo)
      com.didiyun.compute.v1.EbsInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.didiyun.compute.v1.CommonOuterClass.internal_static_didi_cloud_compute_v1_EbsInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.didiyun.compute.v1.CommonOuterClass.internal_static_didi_cloud_compute_v1_EbsInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.didiyun.compute.v1.EbsInfo.class, com.didiyun.compute.v1.EbsInfo.Builder.class);
    }

    // Construct using com.didiyun.compute.v1.EbsInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      ebsUuid_ = "";

      type_ = "";

      attr_ = "";

      ebsTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (regionBuilder_ == null) {
        region_ = null;
      } else {
        region_ = null;
        regionBuilder_ = null;
      }
      deviceName_ = "";

      createTime_ = 0L;

      updateTime_ = 0L;

      if (jobBuilder_ == null) {
        job_ = null;
      } else {
        job_ = null;
        jobBuilder_ = null;
      }
      if (dc2Builder_ == null) {
        dc2_ = null;
      } else {
        dc2_ = null;
        dc2Builder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.didiyun.compute.v1.CommonOuterClass.internal_static_didi_cloud_compute_v1_EbsInfo_descriptor;
    }

    @java.lang.Override
    public com.didiyun.compute.v1.EbsInfo getDefaultInstanceForType() {
      return com.didiyun.compute.v1.EbsInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.didiyun.compute.v1.EbsInfo build() {
      com.didiyun.compute.v1.EbsInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.didiyun.compute.v1.EbsInfo buildPartial() {
      com.didiyun.compute.v1.EbsInfo result = new com.didiyun.compute.v1.EbsInfo(this);
      int from_bitField0_ = bitField0_;
      result.name_ = name_;
      result.ebsUuid_ = ebsUuid_;
      result.type_ = type_;
      result.attr_ = attr_;
      if (((bitField0_ & 0x00000001) != 0)) {
        ebsTags_ = ebsTags_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.ebsTags_ = ebsTags_;
      if (regionBuilder_ == null) {
        result.region_ = region_;
      } else {
        result.region_ = regionBuilder_.build();
      }
      result.deviceName_ = deviceName_;
      result.createTime_ = createTime_;
      result.updateTime_ = updateTime_;
      if (jobBuilder_ == null) {
        result.job_ = job_;
      } else {
        result.job_ = jobBuilder_.build();
      }
      if (dc2Builder_ == null) {
        result.dc2_ = dc2_;
      } else {
        result.dc2_ = dc2Builder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.didiyun.compute.v1.EbsInfo) {
        return mergeFrom((com.didiyun.compute.v1.EbsInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.didiyun.compute.v1.EbsInfo other) {
      if (other == com.didiyun.compute.v1.EbsInfo.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getEbsUuid().isEmpty()) {
        ebsUuid_ = other.ebsUuid_;
        onChanged();
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (!other.getAttr().isEmpty()) {
        attr_ = other.attr_;
        onChanged();
      }
      if (!other.ebsTags_.isEmpty()) {
        if (ebsTags_.isEmpty()) {
          ebsTags_ = other.ebsTags_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureEbsTagsIsMutable();
          ebsTags_.addAll(other.ebsTags_);
        }
        onChanged();
      }
      if (other.hasRegion()) {
        mergeRegion(other.getRegion());
      }
      if (!other.getDeviceName().isEmpty()) {
        deviceName_ = other.deviceName_;
        onChanged();
      }
      if (other.getCreateTime() != 0L) {
        setCreateTime(other.getCreateTime());
      }
      if (other.getUpdateTime() != 0L) {
        setUpdateTime(other.getUpdateTime());
      }
      if (other.hasJob()) {
        mergeJob(other.getJob());
      }
      if (other.hasDc2()) {
        mergeDc2(other.getDc2());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.didiyun.compute.v1.EbsInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.didiyun.compute.v1.EbsInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ebsUuid_ = "";
    /**
     * <code>string ebsUuid = 2;</code>
     * @return The ebsUuid.
     */
    public java.lang.String getEbsUuid() {
      java.lang.Object ref = ebsUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ebsUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ebsUuid = 2;</code>
     * @return The bytes for ebsUuid.
     */
    public com.google.protobuf.ByteString
        getEbsUuidBytes() {
      java.lang.Object ref = ebsUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ebsUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ebsUuid = 2;</code>
     * @param value The ebsUuid to set.
     * @return This builder for chaining.
     */
    public Builder setEbsUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ebsUuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ebsUuid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEbsUuid() {
      
      ebsUuid_ = getDefaultInstance().getEbsUuid();
      onChanged();
      return this;
    }
    /**
     * <code>string ebsUuid = 2;</code>
     * @param value The bytes for ebsUuid to set.
     * @return This builder for chaining.
     */
    public Builder setEbsUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ebsUuid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <pre>
     *种类（SSD、NVMe）
     * </pre>
     *
     * <code>string type = 3;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *种类（SSD、NVMe）
     * </pre>
     *
     * <code>string type = 3;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *种类（SSD、NVMe）
     * </pre>
     *
     * <code>string type = 3;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *种类（SSD、NVMe）
     * </pre>
     *
     * <code>string type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *种类（SSD、NVMe）
     * </pre>
     *
     * <code>string type = 3;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object attr_ = "";
    /**
     * <pre>
     *属性（数据盘、根盘）
     * </pre>
     *
     * <code>string attr = 4;</code>
     * @return The attr.
     */
    public java.lang.String getAttr() {
      java.lang.Object ref = attr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        attr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *属性（数据盘、根盘）
     * </pre>
     *
     * <code>string attr = 4;</code>
     * @return The bytes for attr.
     */
    public com.google.protobuf.ByteString
        getAttrBytes() {
      java.lang.Object ref = attr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        attr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *属性（数据盘、根盘）
     * </pre>
     *
     * <code>string attr = 4;</code>
     * @param value The attr to set.
     * @return This builder for chaining.
     */
    public Builder setAttr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      attr_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *属性（数据盘、根盘）
     * </pre>
     *
     * <code>string attr = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAttr() {
      
      attr_ = getDefaultInstance().getAttr();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *属性（数据盘、根盘）
     * </pre>
     *
     * <code>string attr = 4;</code>
     * @param value The bytes for attr to set.
     * @return This builder for chaining.
     */
    public Builder setAttrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      attr_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList ebsTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureEbsTagsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        ebsTags_ = new com.google.protobuf.LazyStringArrayList(ebsTags_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     *标签
     * </pre>
     *
     * <code>repeated string ebsTags = 5;</code>
     * @return A list containing the ebsTags.
     */
    public com.google.protobuf.ProtocolStringList
        getEbsTagsList() {
      return ebsTags_.getUnmodifiableView();
    }
    /**
     * <pre>
     *标签
     * </pre>
     *
     * <code>repeated string ebsTags = 5;</code>
     * @return The count of ebsTags.
     */
    public int getEbsTagsCount() {
      return ebsTags_.size();
    }
    /**
     * <pre>
     *标签
     * </pre>
     *
     * <code>repeated string ebsTags = 5;</code>
     * @param index The index of the element to return.
     * @return The ebsTags at the given index.
     */
    public java.lang.String getEbsTags(int index) {
      return ebsTags_.get(index);
    }
    /**
     * <pre>
     *标签
     * </pre>
     *
     * <code>repeated string ebsTags = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the ebsTags at the given index.
     */
    public com.google.protobuf.ByteString
        getEbsTagsBytes(int index) {
      return ebsTags_.getByteString(index);
    }
    /**
     * <pre>
     *标签
     * </pre>
     *
     * <code>repeated string ebsTags = 5;</code>
     * @param index The index to set the value at.
     * @param value The ebsTags to set.
     * @return This builder for chaining.
     */
    public Builder setEbsTags(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEbsTagsIsMutable();
      ebsTags_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *标签
     * </pre>
     *
     * <code>repeated string ebsTags = 5;</code>
     * @param value The ebsTags to add.
     * @return This builder for chaining.
     */
    public Builder addEbsTags(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEbsTagsIsMutable();
      ebsTags_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *标签
     * </pre>
     *
     * <code>repeated string ebsTags = 5;</code>
     * @param values The ebsTags to add.
     * @return This builder for chaining.
     */
    public Builder addAllEbsTags(
        java.lang.Iterable<java.lang.String> values) {
      ensureEbsTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, ebsTags_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *标签
     * </pre>
     *
     * <code>repeated string ebsTags = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEbsTags() {
      ebsTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *标签
     * </pre>
     *
     * <code>repeated string ebsTags = 5;</code>
     * @param value The bytes of the ebsTags to add.
     * @return This builder for chaining.
     */
    public Builder addEbsTagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureEbsTagsIsMutable();
      ebsTags_.add(value);
      onChanged();
      return this;
    }

    private com.didiyun.base.v1.RegionAndZoneInfo region_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.didiyun.base.v1.RegionAndZoneInfo, com.didiyun.base.v1.RegionAndZoneInfo.Builder, com.didiyun.base.v1.RegionAndZoneInfoOrBuilder> regionBuilder_;
    /**
     * <pre>
     *region信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.RegionAndZoneInfo region = 6;</code>
     * @return Whether the region field is set.
     */
    public boolean hasRegion() {
      return regionBuilder_ != null || region_ != null;
    }
    /**
     * <pre>
     *region信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.RegionAndZoneInfo region = 6;</code>
     * @return The region.
     */
    public com.didiyun.base.v1.RegionAndZoneInfo getRegion() {
      if (regionBuilder_ == null) {
        return region_ == null ? com.didiyun.base.v1.RegionAndZoneInfo.getDefaultInstance() : region_;
      } else {
        return regionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *region信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.RegionAndZoneInfo region = 6;</code>
     */
    public Builder setRegion(com.didiyun.base.v1.RegionAndZoneInfo value) {
      if (regionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        region_ = value;
        onChanged();
      } else {
        regionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *region信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.RegionAndZoneInfo region = 6;</code>
     */
    public Builder setRegion(
        com.didiyun.base.v1.RegionAndZoneInfo.Builder builderForValue) {
      if (regionBuilder_ == null) {
        region_ = builderForValue.build();
        onChanged();
      } else {
        regionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *region信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.RegionAndZoneInfo region = 6;</code>
     */
    public Builder mergeRegion(com.didiyun.base.v1.RegionAndZoneInfo value) {
      if (regionBuilder_ == null) {
        if (region_ != null) {
          region_ =
            com.didiyun.base.v1.RegionAndZoneInfo.newBuilder(region_).mergeFrom(value).buildPartial();
        } else {
          region_ = value;
        }
        onChanged();
      } else {
        regionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *region信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.RegionAndZoneInfo region = 6;</code>
     */
    public Builder clearRegion() {
      if (regionBuilder_ == null) {
        region_ = null;
        onChanged();
      } else {
        region_ = null;
        regionBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *region信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.RegionAndZoneInfo region = 6;</code>
     */
    public com.didiyun.base.v1.RegionAndZoneInfo.Builder getRegionBuilder() {
      
      onChanged();
      return getRegionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *region信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.RegionAndZoneInfo region = 6;</code>
     */
    public com.didiyun.base.v1.RegionAndZoneInfoOrBuilder getRegionOrBuilder() {
      if (regionBuilder_ != null) {
        return regionBuilder_.getMessageOrBuilder();
      } else {
        return region_ == null ?
            com.didiyun.base.v1.RegionAndZoneInfo.getDefaultInstance() : region_;
      }
    }
    /**
     * <pre>
     *region信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.RegionAndZoneInfo region = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.didiyun.base.v1.RegionAndZoneInfo, com.didiyun.base.v1.RegionAndZoneInfo.Builder, com.didiyun.base.v1.RegionAndZoneInfoOrBuilder> 
        getRegionFieldBuilder() {
      if (regionBuilder_ == null) {
        regionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.didiyun.base.v1.RegionAndZoneInfo, com.didiyun.base.v1.RegionAndZoneInfo.Builder, com.didiyun.base.v1.RegionAndZoneInfoOrBuilder>(
                getRegion(),
                getParentForChildren(),
                isClean());
        region_ = null;
      }
      return regionBuilder_;
    }

    private java.lang.Object deviceName_ = "";
    /**
     * <pre>
     *设备名（盘符）
     * </pre>
     *
     * <code>string deviceName = 7;</code>
     * @return The deviceName.
     */
    public java.lang.String getDeviceName() {
      java.lang.Object ref = deviceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *设备名（盘符）
     * </pre>
     *
     * <code>string deviceName = 7;</code>
     * @return The bytes for deviceName.
     */
    public com.google.protobuf.ByteString
        getDeviceNameBytes() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *设备名（盘符）
     * </pre>
     *
     * <code>string deviceName = 7;</code>
     * @param value The deviceName to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *设备名（盘符）
     * </pre>
     *
     * <code>string deviceName = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceName() {
      
      deviceName_ = getDefaultInstance().getDeviceName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *设备名（盘符）
     * </pre>
     *
     * <code>string deviceName = 7;</code>
     * @param value The bytes for deviceName to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceName_ = value;
      onChanged();
      return this;
    }

    private long createTime_ ;
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>int64 createTime = 8;</code>
     * @return The createTime.
     */
    public long getCreateTime() {
      return createTime_;
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>int64 createTime = 8;</code>
     * @param value The createTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreateTime(long value) {
      
      createTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>int64 createTime = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreateTime() {
      
      createTime_ = 0L;
      onChanged();
      return this;
    }

    private long updateTime_ ;
    /**
     * <pre>
     *更新时间
     * </pre>
     *
     * <code>int64 updateTime = 9;</code>
     * @return The updateTime.
     */
    public long getUpdateTime() {
      return updateTime_;
    }
    /**
     * <pre>
     *更新时间
     * </pre>
     *
     * <code>int64 updateTime = 9;</code>
     * @param value The updateTime to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateTime(long value) {
      
      updateTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *更新时间
     * </pre>
     *
     * <code>int64 updateTime = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdateTime() {
      
      updateTime_ = 0L;
      onChanged();
      return this;
    }

    private com.didiyun.base.v1.JobInfo job_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.didiyun.base.v1.JobInfo, com.didiyun.base.v1.JobInfo.Builder, com.didiyun.base.v1.JobInfoOrBuilder> jobBuilder_;
    /**
     * <pre>
     *任务
     * </pre>
     *
     * <code>.didi.cloud.base.v1.JobInfo job = 10;</code>
     * @return Whether the job field is set.
     */
    public boolean hasJob() {
      return jobBuilder_ != null || job_ != null;
    }
    /**
     * <pre>
     *任务
     * </pre>
     *
     * <code>.didi.cloud.base.v1.JobInfo job = 10;</code>
     * @return The job.
     */
    public com.didiyun.base.v1.JobInfo getJob() {
      if (jobBuilder_ == null) {
        return job_ == null ? com.didiyun.base.v1.JobInfo.getDefaultInstance() : job_;
      } else {
        return jobBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *任务
     * </pre>
     *
     * <code>.didi.cloud.base.v1.JobInfo job = 10;</code>
     */
    public Builder setJob(com.didiyun.base.v1.JobInfo value) {
      if (jobBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        job_ = value;
        onChanged();
      } else {
        jobBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *任务
     * </pre>
     *
     * <code>.didi.cloud.base.v1.JobInfo job = 10;</code>
     */
    public Builder setJob(
        com.didiyun.base.v1.JobInfo.Builder builderForValue) {
      if (jobBuilder_ == null) {
        job_ = builderForValue.build();
        onChanged();
      } else {
        jobBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *任务
     * </pre>
     *
     * <code>.didi.cloud.base.v1.JobInfo job = 10;</code>
     */
    public Builder mergeJob(com.didiyun.base.v1.JobInfo value) {
      if (jobBuilder_ == null) {
        if (job_ != null) {
          job_ =
            com.didiyun.base.v1.JobInfo.newBuilder(job_).mergeFrom(value).buildPartial();
        } else {
          job_ = value;
        }
        onChanged();
      } else {
        jobBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *任务
     * </pre>
     *
     * <code>.didi.cloud.base.v1.JobInfo job = 10;</code>
     */
    public Builder clearJob() {
      if (jobBuilder_ == null) {
        job_ = null;
        onChanged();
      } else {
        job_ = null;
        jobBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *任务
     * </pre>
     *
     * <code>.didi.cloud.base.v1.JobInfo job = 10;</code>
     */
    public com.didiyun.base.v1.JobInfo.Builder getJobBuilder() {
      
      onChanged();
      return getJobFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *任务
     * </pre>
     *
     * <code>.didi.cloud.base.v1.JobInfo job = 10;</code>
     */
    public com.didiyun.base.v1.JobInfoOrBuilder getJobOrBuilder() {
      if (jobBuilder_ != null) {
        return jobBuilder_.getMessageOrBuilder();
      } else {
        return job_ == null ?
            com.didiyun.base.v1.JobInfo.getDefaultInstance() : job_;
      }
    }
    /**
     * <pre>
     *任务
     * </pre>
     *
     * <code>.didi.cloud.base.v1.JobInfo job = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.didiyun.base.v1.JobInfo, com.didiyun.base.v1.JobInfo.Builder, com.didiyun.base.v1.JobInfoOrBuilder> 
        getJobFieldBuilder() {
      if (jobBuilder_ == null) {
        jobBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.didiyun.base.v1.JobInfo, com.didiyun.base.v1.JobInfo.Builder, com.didiyun.base.v1.JobInfoOrBuilder>(
                getJob(),
                getParentForChildren(),
                isClean());
        job_ = null;
      }
      return jobBuilder_;
    }

    private com.didiyun.compute.v1.Dc2Info dc2_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.didiyun.compute.v1.Dc2Info, com.didiyun.compute.v1.Dc2Info.Builder, com.didiyun.compute.v1.Dc2InfoOrBuilder> dc2Builder_;
    /**
     * <pre>
     *与EBS绑定的DC2信息
     * </pre>
     *
     * <code>.didi.cloud.compute.v1.Dc2Info dc2 = 11;</code>
     * @return Whether the dc2 field is set.
     */
    public boolean hasDc2() {
      return dc2Builder_ != null || dc2_ != null;
    }
    /**
     * <pre>
     *与EBS绑定的DC2信息
     * </pre>
     *
     * <code>.didi.cloud.compute.v1.Dc2Info dc2 = 11;</code>
     * @return The dc2.
     */
    public com.didiyun.compute.v1.Dc2Info getDc2() {
      if (dc2Builder_ == null) {
        return dc2_ == null ? com.didiyun.compute.v1.Dc2Info.getDefaultInstance() : dc2_;
      } else {
        return dc2Builder_.getMessage();
      }
    }
    /**
     * <pre>
     *与EBS绑定的DC2信息
     * </pre>
     *
     * <code>.didi.cloud.compute.v1.Dc2Info dc2 = 11;</code>
     */
    public Builder setDc2(com.didiyun.compute.v1.Dc2Info value) {
      if (dc2Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dc2_ = value;
        onChanged();
      } else {
        dc2Builder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *与EBS绑定的DC2信息
     * </pre>
     *
     * <code>.didi.cloud.compute.v1.Dc2Info dc2 = 11;</code>
     */
    public Builder setDc2(
        com.didiyun.compute.v1.Dc2Info.Builder builderForValue) {
      if (dc2Builder_ == null) {
        dc2_ = builderForValue.build();
        onChanged();
      } else {
        dc2Builder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *与EBS绑定的DC2信息
     * </pre>
     *
     * <code>.didi.cloud.compute.v1.Dc2Info dc2 = 11;</code>
     */
    public Builder mergeDc2(com.didiyun.compute.v1.Dc2Info value) {
      if (dc2Builder_ == null) {
        if (dc2_ != null) {
          dc2_ =
            com.didiyun.compute.v1.Dc2Info.newBuilder(dc2_).mergeFrom(value).buildPartial();
        } else {
          dc2_ = value;
        }
        onChanged();
      } else {
        dc2Builder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *与EBS绑定的DC2信息
     * </pre>
     *
     * <code>.didi.cloud.compute.v1.Dc2Info dc2 = 11;</code>
     */
    public Builder clearDc2() {
      if (dc2Builder_ == null) {
        dc2_ = null;
        onChanged();
      } else {
        dc2_ = null;
        dc2Builder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *与EBS绑定的DC2信息
     * </pre>
     *
     * <code>.didi.cloud.compute.v1.Dc2Info dc2 = 11;</code>
     */
    public com.didiyun.compute.v1.Dc2Info.Builder getDc2Builder() {
      
      onChanged();
      return getDc2FieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *与EBS绑定的DC2信息
     * </pre>
     *
     * <code>.didi.cloud.compute.v1.Dc2Info dc2 = 11;</code>
     */
    public com.didiyun.compute.v1.Dc2InfoOrBuilder getDc2OrBuilder() {
      if (dc2Builder_ != null) {
        return dc2Builder_.getMessageOrBuilder();
      } else {
        return dc2_ == null ?
            com.didiyun.compute.v1.Dc2Info.getDefaultInstance() : dc2_;
      }
    }
    /**
     * <pre>
     *与EBS绑定的DC2信息
     * </pre>
     *
     * <code>.didi.cloud.compute.v1.Dc2Info dc2 = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.didiyun.compute.v1.Dc2Info, com.didiyun.compute.v1.Dc2Info.Builder, com.didiyun.compute.v1.Dc2InfoOrBuilder> 
        getDc2FieldBuilder() {
      if (dc2Builder_ == null) {
        dc2Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.didiyun.compute.v1.Dc2Info, com.didiyun.compute.v1.Dc2Info.Builder, com.didiyun.compute.v1.Dc2InfoOrBuilder>(
                getDc2(),
                getParentForChildren(),
                isClean());
        dc2_ = null;
      }
      return dc2Builder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:didi.cloud.compute.v1.EbsInfo)
  }

  // @@protoc_insertion_point(class_scope:didi.cloud.compute.v1.EbsInfo)
  private static final com.didiyun.compute.v1.EbsInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.didiyun.compute.v1.EbsInfo();
  }

  public static com.didiyun.compute.v1.EbsInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EbsInfo>
      PARSER = new com.google.protobuf.AbstractParser<EbsInfo>() {
    @java.lang.Override
    public EbsInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EbsInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EbsInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EbsInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.didiyun.compute.v1.EbsInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

