// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/cport.proto

package com.didiyun.compute.v1;

public interface GetCportByUuidRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.GetCportByUuidRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   * @return The header.
   */
  com.didiyun.base.v1.Header getHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  com.didiyun.base.v1.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   *容器port的Uuid
   * </pre>
   *
   * <code>string cportUuid = 2;</code>
   * @return The cportUuid.
   */
  java.lang.String getCportUuid();
  /**
   * <pre>
   *容器port的Uuid
   * </pre>
   *
   * <code>string cportUuid = 2;</code>
   * @return The bytes for cportUuid.
   */
  com.google.protobuf.ByteString
      getCportUuidBytes();
}
