// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/dc2.proto

package com.didiyun.compute.v1;

public interface GetDc2ByUuidRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.GetDc2ByUuidRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   * @return The header.
   */
  com.didiyun.base.v1.Header getHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  com.didiyun.base.v1.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   *dc2的Uuid
   * </pre>
   *
   * <code>string dc2Uuid = 2;</code>
   * @return The dc2Uuid.
   */
  java.lang.String getDc2Uuid();
  /**
   * <pre>
   *dc2的Uuid
   * </pre>
   *
   * <code>string dc2Uuid = 2;</code>
   * @return The bytes for dc2Uuid.
   */
  com.google.protobuf.ByteString
      getDc2UuidBytes();
}
