// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/eip.proto

package com.didiyun.compute.v1;

public interface GetEipTotalCntRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.GetEipTotalCntRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   * @return The header.
   */
  com.didiyun.base.v1.Header getHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  com.didiyun.base.v1.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   *精确匹配EIP
   * </pre>
   *
   * <code>string eip = 2;</code>
   * @return The eip.
   */
  java.lang.String getEip();
  /**
   * <pre>
   *精确匹配EIP
   * </pre>
   *
   * <code>string eip = 2;</code>
   * @return The bytes for eip.
   */
  com.google.protobuf.ByteString
      getEipBytes();

  /**
   * <pre>
   *查询指定EIP的信息,UUID
   * </pre>
   *
   * <code>repeated string eipUuids = 3;</code>
   * @return A list containing the eipUuids.
   */
  java.util.List<java.lang.String>
      getEipUuidsList();
  /**
   * <pre>
   *查询指定EIP的信息,UUID
   * </pre>
   *
   * <code>repeated string eipUuids = 3;</code>
   * @return The count of eipUuids.
   */
  int getEipUuidsCount();
  /**
   * <pre>
   *查询指定EIP的信息,UUID
   * </pre>
   *
   * <code>repeated string eipUuids = 3;</code>
   * @param index The index of the element to return.
   * @return The eipUuids at the given index.
   */
  java.lang.String getEipUuids(int index);
  /**
   * <pre>
   *查询指定EIP的信息,UUID
   * </pre>
   *
   * <code>repeated string eipUuids = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the eipUuids at the given index.
   */
  com.google.protobuf.ByteString
      getEipUuidsBytes(int index);
}
