// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/ebs.proto

package com.didiyun.compute.v1;

public interface GetEbsByUuidRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.GetEbsByUuidRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   * @return The header.
   */
  com.didiyun.base.v1.Header getHeader();
  /**
   * <pre>
   *公共的请求头
   * </pre>
   *
   * <code>.didi.cloud.base.v1.Header header = 1;</code>
   */
  com.didiyun.base.v1.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   *EBS的uuid
   * </pre>
   *
   * <code>string ebsUuid = 2;</code>
   * @return The ebsUuid.
   */
  java.lang.String getEbsUuid();
  /**
   * <pre>
   *EBS的uuid
   * </pre>
   *
   * <code>string ebsUuid = 2;</code>
   * @return The bytes for ebsUuid.
   */
  com.google.protobuf.ByteString
      getEbsUuidBytes();
}
