// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/vpc.proto

package com.didiyun.compute.v1;

public interface ListSubnetConditionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.ListSubnetCondition)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string vpcUuid = 1;</code>
   * @return The vpcUuid.
   */
  java.lang.String getVpcUuid();
  /**
   * <code>string vpcUuid = 1;</code>
   * @return The bytes for vpcUuid.
   */
  com.google.protobuf.ByteString
      getVpcUuidBytes();
}
