// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/cport.proto

package com.didiyun.compute.v1;

public interface ListCportResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.ListCportResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.didi.cloud.base.v1.Error error = 1;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.didi.cloud.base.v1.Error error = 1;</code>
   * @return The error.
   */
  com.didiyun.base.v1.Error getError();
  /**
   * <code>.didi.cloud.base.v1.Error error = 1;</code>
   */
  com.didiyun.base.v1.ErrorOrBuilder getErrorOrBuilder();

  /**
   * <code>.didi.cloud.compute.v1.ListCportData data = 2;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.didi.cloud.compute.v1.ListCportData data = 2;</code>
   * @return The data.
   */
  com.didiyun.compute.v1.ListCportData getData();
  /**
   * <code>.didi.cloud.compute.v1.ListCportData data = 2;</code>
   */
  com.didiyun.compute.v1.ListCportDataOrBuilder getDataOrBuilder();
}
