// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/ebs.proto

package com.didiyun.compute.v1;

public interface ListEbsConditionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.ListEbsCondition)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *DC2唯一标识
   * </pre>
   *
   * <code>repeated string dc2Uuids = 1;</code>
   * @return A list containing the dc2Uuids.
   */
  java.util.List<java.lang.String>
      getDc2UuidsList();
  /**
   * <pre>
   *DC2唯一标识
   * </pre>
   *
   * <code>repeated string dc2Uuids = 1;</code>
   * @return The count of dc2Uuids.
   */
  int getDc2UuidsCount();
  /**
   * <pre>
   *DC2唯一标识
   * </pre>
   *
   * <code>repeated string dc2Uuids = 1;</code>
   * @param index The index of the element to return.
   * @return The dc2Uuids at the given index.
   */
  java.lang.String getDc2Uuids(int index);
  /**
   * <pre>
   *DC2唯一标识
   * </pre>
   *
   * <code>repeated string dc2Uuids = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the dc2Uuids at the given index.
   */
  com.google.protobuf.ByteString
      getDc2UuidsBytes(int index);
}
