// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/common.proto

package com.didiyun.compute.v1;

public interface SgInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.SgInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Sg唯一标识
   * </pre>
   *
   * <code>string sgUuid = 1;</code>
   * @return The sgUuid.
   */
  java.lang.String getSgUuid();
  /**
   * <pre>
   *Sg唯一标识
   * </pre>
   *
   * <code>string sgUuid = 1;</code>
   * @return The bytes for sgUuid.
   */
  com.google.protobuf.ByteString
      getSgUuidBytes();

  /**
   * <pre>
   *Sg名称
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *Sg名称
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *Sg创建时间
   * </pre>
   *
   * <code>int64 createTime = 3;</code>
   * @return The createTime.
   */
  long getCreateTime();

  /**
   * <pre>
   *Sg更新时间
   * </pre>
   *
   * <code>int64 updateTime = 4;</code>
   * @return The updateTime.
   */
  long getUpdateTime();

  /**
   * <pre>
   *Sg是否是当前VPC下的默认Sg
   * </pre>
   *
   * <code>bool isDefault = 5;</code>
   * @return The isDefault.
   */
  boolean getIsDefault();

  /**
   * <pre>
   *Sg绑定的DC2数量
   * </pre>
   *
   * <code>int64 dc2Cnt = 6;</code>
   * @return The dc2Cnt.
   */
  long getDc2Cnt();

  /**
   * <pre>
   *Sg包含的Sg规则数量
   * </pre>
   *
   * <code>int64 sgRuleCnt = 7;</code>
   * @return The sgRuleCnt.
   */
  long getSgRuleCnt();

  /**
   * <pre>
   *Sg所属的VPC信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.VpcInfo vpc = 8;</code>
   * @return Whether the vpc field is set.
   */
  boolean hasVpc();
  /**
   * <pre>
   *Sg所属的VPC信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.VpcInfo vpc = 8;</code>
   * @return The vpc.
   */
  com.didiyun.compute.v1.VpcInfo getVpc();
  /**
   * <pre>
   *Sg所属的VPC信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.VpcInfo vpc = 8;</code>
   */
  com.didiyun.compute.v1.VpcInfoOrBuilder getVpcOrBuilder();

  /**
   * <pre>
   *Sg所在的Region信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.RegionInfo region = 9;</code>
   * @return Whether the region field is set.
   */
  boolean hasRegion();
  /**
   * <pre>
   *Sg所在的Region信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.RegionInfo region = 9;</code>
   * @return The region.
   */
  com.didiyun.base.v1.RegionInfo getRegion();
  /**
   * <pre>
   *Sg所在的Region信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.RegionInfo region = 9;</code>
   */
  com.didiyun.base.v1.RegionInfoOrBuilder getRegionOrBuilder();

  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 10;</code>
   * @return Whether the job field is set.
   */
  boolean hasJob();
  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 10;</code>
   * @return The job.
   */
  com.didiyun.base.v1.JobInfo getJob();
  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 10;</code>
   */
  com.didiyun.base.v1.JobInfoOrBuilder getJobOrBuilder();
}
