// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/common.proto

package com.didiyun.compute.v1;

public interface SgRuleInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.SgRuleInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *SgRule唯一标识
   * </pre>
   *
   * <code>string sgRuleUuid = 1;</code>
   * @return The sgRuleUuid.
   */
  java.lang.String getSgRuleUuid();
  /**
   * <pre>
   *SgRule唯一标识
   * </pre>
   *
   * <code>string sgRuleUuid = 1;</code>
   * @return The bytes for sgRuleUuid.
   */
  com.google.protobuf.ByteString
      getSgRuleUuidBytes();

  /**
   * <pre>
   *SgRule创建时间
   * </pre>
   *
   * <code>int64 createTime = 2;</code>
   * @return The createTime.
   */
  long getCreateTime();

  /**
   * <pre>
   *SgRule更新时间
   * </pre>
   *
   * <code>int64 updateTime = 3;</code>
   * @return The updateTime.
   */
  long getUpdateTime();

  /**
   * <pre>
   *SgRule类型，"Ingress"表示入方向，"Egress"表示出方向
   * </pre>
   *
   * <code>string type = 4;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   *SgRule类型，"Ingress"表示入方向，"Egress"表示出方向
   * </pre>
   *
   * <code>string type = 4;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <pre>
   *SgRule支持的协议，"TCP"、"UDP"或"ICMP"
   * </pre>
   *
   * <code>string protocol = 5;</code>
   * @return The protocol.
   */
  java.lang.String getProtocol();
  /**
   * <pre>
   *SgRule支持的协议，"TCP"、"UDP"或"ICMP"
   * </pre>
   *
   * <code>string protocol = 5;</code>
   * @return The bytes for protocol.
   */
  com.google.protobuf.ByteString
      getProtocolBytes();

  /**
   * <pre>
   *SgRule允许端口从startPort值开始，在0-65535之间
   * </pre>
   *
   * <code>int64 startPort = 6;</code>
   * @return The startPort.
   */
  long getStartPort();

  /**
   * <pre>
   *SgRule允许端口从endPort结束，当等于startPort时，表示SGRule只对startPort的端口开放，在0-65535之间
   * </pre>
   *
   * <code>int64 endPort = 7;</code>
   * @return The endPort.
   */
  long getEndPort();

  /**
   * <pre>
   *SgRule允许的网段
   * </pre>
   *
   * <code>string allowedCidr = 8;</code>
   * @return The allowedCidr.
   */
  java.lang.String getAllowedCidr();
  /**
   * <pre>
   *SgRule允许的网段
   * </pre>
   *
   * <code>string allowedCidr = 8;</code>
   * @return The bytes for allowedCidr.
   */
  com.google.protobuf.ByteString
      getAllowedCidrBytes();

  /**
   * <pre>
   *SgRule是否为所属Sg下的默认SgRule
   * </pre>
   *
   * <code>bool isDefault = 9;</code>
   * @return The isDefault.
   */
  boolean getIsDefault();

  /**
   * <pre>
   *SgRule所属的Sg信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.SgInfo sg = 10;</code>
   * @return Whether the sg field is set.
   */
  boolean hasSg();
  /**
   * <pre>
   *SgRule所属的Sg信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.SgInfo sg = 10;</code>
   * @return The sg.
   */
  com.didiyun.compute.v1.SgInfo getSg();
  /**
   * <pre>
   *SgRule所属的Sg信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.SgInfo sg = 10;</code>
   */
  com.didiyun.compute.v1.SgInfoOrBuilder getSgOrBuilder();

  /**
   * <pre>
   *SgRule所属的Vpc信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.VpcInfo vpc = 11;</code>
   * @return Whether the vpc field is set.
   */
  boolean hasVpc();
  /**
   * <pre>
   *SgRule所属的Vpc信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.VpcInfo vpc = 11;</code>
   * @return The vpc.
   */
  com.didiyun.compute.v1.VpcInfo getVpc();
  /**
   * <pre>
   *SgRule所属的Vpc信息
   * </pre>
   *
   * <code>.didi.cloud.compute.v1.VpcInfo vpc = 11;</code>
   */
  com.didiyun.compute.v1.VpcInfoOrBuilder getVpcOrBuilder();

  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
   * @return Whether the job field is set.
   */
  boolean hasJob();
  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
   * @return The job.
   */
  com.didiyun.base.v1.JobInfo getJob();
  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 12;</code>
   */
  com.didiyun.base.v1.JobInfoOrBuilder getJobOrBuilder();
}
