// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/common.proto

package com.didiyun.compute.v1;

/**
 * Protobuf type {@code didi.cloud.compute.v1.SubnetInfo}
 */
public  final class SubnetInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:didi.cloud.compute.v1.SubnetInfo)
    SubnetInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubnetInfo.newBuilder() to construct.
  private SubnetInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubnetInfo() {
    subnetUuid_ = "";
    name_ = "";
    cidr_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SubnetInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SubnetInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            subnetUuid_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {

            createTime_ = input.readInt64();
            break;
          }
          case 32: {

            updateTime_ = input.readInt64();
            break;
          }
          case 40: {

            isDefault_ = input.readBool();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            cidr_ = s;
            break;
          }
          case 58: {
            com.didiyun.base.v1.ZoneInfo.Builder subBuilder = null;
            if (zone_ != null) {
              subBuilder = zone_.toBuilder();
            }
            zone_ = input.readMessage(com.didiyun.base.v1.ZoneInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(zone_);
              zone_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.didiyun.compute.v1.CommonOuterClass.internal_static_didi_cloud_compute_v1_SubnetInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.didiyun.compute.v1.CommonOuterClass.internal_static_didi_cloud_compute_v1_SubnetInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.didiyun.compute.v1.SubnetInfo.class, com.didiyun.compute.v1.SubnetInfo.Builder.class);
  }

  public static final int SUBNETUUID_FIELD_NUMBER = 1;
  private volatile java.lang.Object subnetUuid_;
  /**
   * <pre>
   *Subnet唯一标识
   * </pre>
   *
   * <code>string subnetUuid = 1;</code>
   * @return The subnetUuid.
   */
  public java.lang.String getSubnetUuid() {
    java.lang.Object ref = subnetUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      subnetUuid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *Subnet唯一标识
   * </pre>
   *
   * <code>string subnetUuid = 1;</code>
   * @return The bytes for subnetUuid.
   */
  public com.google.protobuf.ByteString
      getSubnetUuidBytes() {
    java.lang.Object ref = subnetUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      subnetUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   *Subnet名称
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *Subnet名称
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATETIME_FIELD_NUMBER = 3;
  private long createTime_;
  /**
   * <pre>
   *Subnet创建时间
   * </pre>
   *
   * <code>int64 createTime = 3;</code>
   * @return The createTime.
   */
  public long getCreateTime() {
    return createTime_;
  }

  public static final int UPDATETIME_FIELD_NUMBER = 4;
  private long updateTime_;
  /**
   * <pre>
   *Subnet更新时间
   * </pre>
   *
   * <code>int64 updateTime = 4;</code>
   * @return The updateTime.
   */
  public long getUpdateTime() {
    return updateTime_;
  }

  public static final int ISDEFAULT_FIELD_NUMBER = 5;
  private boolean isDefault_;
  /**
   * <pre>
   *Subent是否是zone下的默认subnet
   * </pre>
   *
   * <code>bool isDefault = 5;</code>
   * @return The isDefault.
   */
  public boolean getIsDefault() {
    return isDefault_;
  }

  public static final int CIDR_FIELD_NUMBER = 6;
  private volatile java.lang.Object cidr_;
  /**
   * <pre>
   *Subnet的网段
   * </pre>
   *
   * <code>string cidr = 6;</code>
   * @return The cidr.
   */
  public java.lang.String getCidr() {
    java.lang.Object ref = cidr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cidr_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *Subnet的网段
   * </pre>
   *
   * <code>string cidr = 6;</code>
   * @return The bytes for cidr.
   */
  public com.google.protobuf.ByteString
      getCidrBytes() {
    java.lang.Object ref = cidr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cidr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ZONE_FIELD_NUMBER = 7;
  private com.didiyun.base.v1.ZoneInfo zone_;
  /**
   * <pre>
   *Subent所在的Zone信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.ZoneInfo zone = 7;</code>
   * @return Whether the zone field is set.
   */
  public boolean hasZone() {
    return zone_ != null;
  }
  /**
   * <pre>
   *Subent所在的Zone信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.ZoneInfo zone = 7;</code>
   * @return The zone.
   */
  public com.didiyun.base.v1.ZoneInfo getZone() {
    return zone_ == null ? com.didiyun.base.v1.ZoneInfo.getDefaultInstance() : zone_;
  }
  /**
   * <pre>
   *Subent所在的Zone信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.ZoneInfo zone = 7;</code>
   */
  public com.didiyun.base.v1.ZoneInfoOrBuilder getZoneOrBuilder() {
    return getZone();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSubnetUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, subnetUuid_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (createTime_ != 0L) {
      output.writeInt64(3, createTime_);
    }
    if (updateTime_ != 0L) {
      output.writeInt64(4, updateTime_);
    }
    if (isDefault_ != false) {
      output.writeBool(5, isDefault_);
    }
    if (!getCidrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, cidr_);
    }
    if (zone_ != null) {
      output.writeMessage(7, getZone());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSubnetUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, subnetUuid_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (createTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, createTime_);
    }
    if (updateTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, updateTime_);
    }
    if (isDefault_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isDefault_);
    }
    if (!getCidrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, cidr_);
    }
    if (zone_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getZone());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.didiyun.compute.v1.SubnetInfo)) {
      return super.equals(obj);
    }
    com.didiyun.compute.v1.SubnetInfo other = (com.didiyun.compute.v1.SubnetInfo) obj;

    if (!getSubnetUuid()
        .equals(other.getSubnetUuid())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (getCreateTime()
        != other.getCreateTime()) return false;
    if (getUpdateTime()
        != other.getUpdateTime()) return false;
    if (getIsDefault()
        != other.getIsDefault()) return false;
    if (!getCidr()
        .equals(other.getCidr())) return false;
    if (hasZone() != other.hasZone()) return false;
    if (hasZone()) {
      if (!getZone()
          .equals(other.getZone())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUBNETUUID_FIELD_NUMBER;
    hash = (53 * hash) + getSubnetUuid().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreateTime());
    hash = (37 * hash) + UPDATETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUpdateTime());
    hash = (37 * hash) + ISDEFAULT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsDefault());
    hash = (37 * hash) + CIDR_FIELD_NUMBER;
    hash = (53 * hash) + getCidr().hashCode();
    if (hasZone()) {
      hash = (37 * hash) + ZONE_FIELD_NUMBER;
      hash = (53 * hash) + getZone().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.didiyun.compute.v1.SubnetInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.compute.v1.SubnetInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.compute.v1.SubnetInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.compute.v1.SubnetInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.compute.v1.SubnetInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.didiyun.compute.v1.SubnetInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.didiyun.compute.v1.SubnetInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.didiyun.compute.v1.SubnetInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.didiyun.compute.v1.SubnetInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.didiyun.compute.v1.SubnetInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.didiyun.compute.v1.SubnetInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.didiyun.compute.v1.SubnetInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.didiyun.compute.v1.SubnetInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code didi.cloud.compute.v1.SubnetInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:didi.cloud.compute.v1.SubnetInfo)
      com.didiyun.compute.v1.SubnetInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.didiyun.compute.v1.CommonOuterClass.internal_static_didi_cloud_compute_v1_SubnetInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.didiyun.compute.v1.CommonOuterClass.internal_static_didi_cloud_compute_v1_SubnetInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.didiyun.compute.v1.SubnetInfo.class, com.didiyun.compute.v1.SubnetInfo.Builder.class);
    }

    // Construct using com.didiyun.compute.v1.SubnetInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      subnetUuid_ = "";

      name_ = "";

      createTime_ = 0L;

      updateTime_ = 0L;

      isDefault_ = false;

      cidr_ = "";

      if (zoneBuilder_ == null) {
        zone_ = null;
      } else {
        zone_ = null;
        zoneBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.didiyun.compute.v1.CommonOuterClass.internal_static_didi_cloud_compute_v1_SubnetInfo_descriptor;
    }

    @java.lang.Override
    public com.didiyun.compute.v1.SubnetInfo getDefaultInstanceForType() {
      return com.didiyun.compute.v1.SubnetInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.didiyun.compute.v1.SubnetInfo build() {
      com.didiyun.compute.v1.SubnetInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.didiyun.compute.v1.SubnetInfo buildPartial() {
      com.didiyun.compute.v1.SubnetInfo result = new com.didiyun.compute.v1.SubnetInfo(this);
      result.subnetUuid_ = subnetUuid_;
      result.name_ = name_;
      result.createTime_ = createTime_;
      result.updateTime_ = updateTime_;
      result.isDefault_ = isDefault_;
      result.cidr_ = cidr_;
      if (zoneBuilder_ == null) {
        result.zone_ = zone_;
      } else {
        result.zone_ = zoneBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.didiyun.compute.v1.SubnetInfo) {
        return mergeFrom((com.didiyun.compute.v1.SubnetInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.didiyun.compute.v1.SubnetInfo other) {
      if (other == com.didiyun.compute.v1.SubnetInfo.getDefaultInstance()) return this;
      if (!other.getSubnetUuid().isEmpty()) {
        subnetUuid_ = other.subnetUuid_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getCreateTime() != 0L) {
        setCreateTime(other.getCreateTime());
      }
      if (other.getUpdateTime() != 0L) {
        setUpdateTime(other.getUpdateTime());
      }
      if (other.getIsDefault() != false) {
        setIsDefault(other.getIsDefault());
      }
      if (!other.getCidr().isEmpty()) {
        cidr_ = other.cidr_;
        onChanged();
      }
      if (other.hasZone()) {
        mergeZone(other.getZone());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.didiyun.compute.v1.SubnetInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.didiyun.compute.v1.SubnetInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object subnetUuid_ = "";
    /**
     * <pre>
     *Subnet唯一标识
     * </pre>
     *
     * <code>string subnetUuid = 1;</code>
     * @return The subnetUuid.
     */
    public java.lang.String getSubnetUuid() {
      java.lang.Object ref = subnetUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subnetUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *Subnet唯一标识
     * </pre>
     *
     * <code>string subnetUuid = 1;</code>
     * @return The bytes for subnetUuid.
     */
    public com.google.protobuf.ByteString
        getSubnetUuidBytes() {
      java.lang.Object ref = subnetUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subnetUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *Subnet唯一标识
     * </pre>
     *
     * <code>string subnetUuid = 1;</code>
     * @param value The subnetUuid to set.
     * @return This builder for chaining.
     */
    public Builder setSubnetUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      subnetUuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Subnet唯一标识
     * </pre>
     *
     * <code>string subnetUuid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubnetUuid() {
      
      subnetUuid_ = getDefaultInstance().getSubnetUuid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Subnet唯一标识
     * </pre>
     *
     * <code>string subnetUuid = 1;</code>
     * @param value The bytes for subnetUuid to set.
     * @return This builder for chaining.
     */
    public Builder setSubnetUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      subnetUuid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     *Subnet名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *Subnet名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *Subnet名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Subnet名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Subnet名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private long createTime_ ;
    /**
     * <pre>
     *Subnet创建时间
     * </pre>
     *
     * <code>int64 createTime = 3;</code>
     * @return The createTime.
     */
    public long getCreateTime() {
      return createTime_;
    }
    /**
     * <pre>
     *Subnet创建时间
     * </pre>
     *
     * <code>int64 createTime = 3;</code>
     * @param value The createTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreateTime(long value) {
      
      createTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Subnet创建时间
     * </pre>
     *
     * <code>int64 createTime = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreateTime() {
      
      createTime_ = 0L;
      onChanged();
      return this;
    }

    private long updateTime_ ;
    /**
     * <pre>
     *Subnet更新时间
     * </pre>
     *
     * <code>int64 updateTime = 4;</code>
     * @return The updateTime.
     */
    public long getUpdateTime() {
      return updateTime_;
    }
    /**
     * <pre>
     *Subnet更新时间
     * </pre>
     *
     * <code>int64 updateTime = 4;</code>
     * @param value The updateTime to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateTime(long value) {
      
      updateTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Subnet更新时间
     * </pre>
     *
     * <code>int64 updateTime = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdateTime() {
      
      updateTime_ = 0L;
      onChanged();
      return this;
    }

    private boolean isDefault_ ;
    /**
     * <pre>
     *Subent是否是zone下的默认subnet
     * </pre>
     *
     * <code>bool isDefault = 5;</code>
     * @return The isDefault.
     */
    public boolean getIsDefault() {
      return isDefault_;
    }
    /**
     * <pre>
     *Subent是否是zone下的默认subnet
     * </pre>
     *
     * <code>bool isDefault = 5;</code>
     * @param value The isDefault to set.
     * @return This builder for chaining.
     */
    public Builder setIsDefault(boolean value) {
      
      isDefault_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Subent是否是zone下的默认subnet
     * </pre>
     *
     * <code>bool isDefault = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsDefault() {
      
      isDefault_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object cidr_ = "";
    /**
     * <pre>
     *Subnet的网段
     * </pre>
     *
     * <code>string cidr = 6;</code>
     * @return The cidr.
     */
    public java.lang.String getCidr() {
      java.lang.Object ref = cidr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cidr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *Subnet的网段
     * </pre>
     *
     * <code>string cidr = 6;</code>
     * @return The bytes for cidr.
     */
    public com.google.protobuf.ByteString
        getCidrBytes() {
      java.lang.Object ref = cidr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cidr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *Subnet的网段
     * </pre>
     *
     * <code>string cidr = 6;</code>
     * @param value The cidr to set.
     * @return This builder for chaining.
     */
    public Builder setCidr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cidr_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Subnet的网段
     * </pre>
     *
     * <code>string cidr = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCidr() {
      
      cidr_ = getDefaultInstance().getCidr();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Subnet的网段
     * </pre>
     *
     * <code>string cidr = 6;</code>
     * @param value The bytes for cidr to set.
     * @return This builder for chaining.
     */
    public Builder setCidrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cidr_ = value;
      onChanged();
      return this;
    }

    private com.didiyun.base.v1.ZoneInfo zone_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.didiyun.base.v1.ZoneInfo, com.didiyun.base.v1.ZoneInfo.Builder, com.didiyun.base.v1.ZoneInfoOrBuilder> zoneBuilder_;
    /**
     * <pre>
     *Subent所在的Zone信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.ZoneInfo zone = 7;</code>
     * @return Whether the zone field is set.
     */
    public boolean hasZone() {
      return zoneBuilder_ != null || zone_ != null;
    }
    /**
     * <pre>
     *Subent所在的Zone信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.ZoneInfo zone = 7;</code>
     * @return The zone.
     */
    public com.didiyun.base.v1.ZoneInfo getZone() {
      if (zoneBuilder_ == null) {
        return zone_ == null ? com.didiyun.base.v1.ZoneInfo.getDefaultInstance() : zone_;
      } else {
        return zoneBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *Subent所在的Zone信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.ZoneInfo zone = 7;</code>
     */
    public Builder setZone(com.didiyun.base.v1.ZoneInfo value) {
      if (zoneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        zone_ = value;
        onChanged();
      } else {
        zoneBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *Subent所在的Zone信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.ZoneInfo zone = 7;</code>
     */
    public Builder setZone(
        com.didiyun.base.v1.ZoneInfo.Builder builderForValue) {
      if (zoneBuilder_ == null) {
        zone_ = builderForValue.build();
        onChanged();
      } else {
        zoneBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *Subent所在的Zone信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.ZoneInfo zone = 7;</code>
     */
    public Builder mergeZone(com.didiyun.base.v1.ZoneInfo value) {
      if (zoneBuilder_ == null) {
        if (zone_ != null) {
          zone_ =
            com.didiyun.base.v1.ZoneInfo.newBuilder(zone_).mergeFrom(value).buildPartial();
        } else {
          zone_ = value;
        }
        onChanged();
      } else {
        zoneBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *Subent所在的Zone信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.ZoneInfo zone = 7;</code>
     */
    public Builder clearZone() {
      if (zoneBuilder_ == null) {
        zone_ = null;
        onChanged();
      } else {
        zone_ = null;
        zoneBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *Subent所在的Zone信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.ZoneInfo zone = 7;</code>
     */
    public com.didiyun.base.v1.ZoneInfo.Builder getZoneBuilder() {
      
      onChanged();
      return getZoneFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *Subent所在的Zone信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.ZoneInfo zone = 7;</code>
     */
    public com.didiyun.base.v1.ZoneInfoOrBuilder getZoneOrBuilder() {
      if (zoneBuilder_ != null) {
        return zoneBuilder_.getMessageOrBuilder();
      } else {
        return zone_ == null ?
            com.didiyun.base.v1.ZoneInfo.getDefaultInstance() : zone_;
      }
    }
    /**
     * <pre>
     *Subent所在的Zone信息
     * </pre>
     *
     * <code>.didi.cloud.base.v1.ZoneInfo zone = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.didiyun.base.v1.ZoneInfo, com.didiyun.base.v1.ZoneInfo.Builder, com.didiyun.base.v1.ZoneInfoOrBuilder> 
        getZoneFieldBuilder() {
      if (zoneBuilder_ == null) {
        zoneBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.didiyun.base.v1.ZoneInfo, com.didiyun.base.v1.ZoneInfo.Builder, com.didiyun.base.v1.ZoneInfoOrBuilder>(
                getZone(),
                getParentForChildren(),
                isClean());
        zone_ = null;
      }
      return zoneBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:didi.cloud.compute.v1.SubnetInfo)
  }

  // @@protoc_insertion_point(class_scope:didi.cloud.compute.v1.SubnetInfo)
  private static final com.didiyun.compute.v1.SubnetInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.didiyun.compute.v1.SubnetInfo();
  }

  public static com.didiyun.compute.v1.SubnetInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubnetInfo>
      PARSER = new com.google.protobuf.AbstractParser<SubnetInfo>() {
    @java.lang.Override
    public SubnetInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SubnetInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SubnetInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubnetInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.didiyun.compute.v1.SubnetInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

