// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/vpc.proto

package com.didiyun.compute.v1;

public interface VpcAvailableCidrOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.VpcAvailableCidr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *可用网段
   * </pre>
   *
   * <code>repeated string availableCidr = 1;</code>
   * @return A list containing the availableCidr.
   */
  java.util.List<java.lang.String>
      getAvailableCidrList();
  /**
   * <pre>
   *可用网段
   * </pre>
   *
   * <code>repeated string availableCidr = 1;</code>
   * @return The count of availableCidr.
   */
  int getAvailableCidrCount();
  /**
   * <pre>
   *可用网段
   * </pre>
   *
   * <code>repeated string availableCidr = 1;</code>
   * @param index The index of the element to return.
   * @return The availableCidr at the given index.
   */
  java.lang.String getAvailableCidr(int index);
  /**
   * <pre>
   *可用网段
   * </pre>
   *
   * <code>repeated string availableCidr = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the availableCidr at the given index.
   */
  com.google.protobuf.ByteString
      getAvailableCidrBytes(int index);
}
