// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/v1/common.proto

package com.didiyun.compute.v1;

public interface VpcInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.compute.v1.VpcInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *VPC唯一标识
   * </pre>
   *
   * <code>string vpcUuid = 1;</code>
   * @return The vpcUuid.
   */
  java.lang.String getVpcUuid();
  /**
   * <pre>
   *VPC唯一标识
   * </pre>
   *
   * <code>string vpcUuid = 1;</code>
   * @return The bytes for vpcUuid.
   */
  com.google.protobuf.ByteString
      getVpcUuidBytes();

  /**
   * <pre>
   *VPC名称
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *VPC名称
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *VPC创建时间
   * </pre>
   *
   * <code>int64 createTime = 3;</code>
   * @return The createTime.
   */
  long getCreateTime();

  /**
   * <pre>
   *VPC更新时间
   * </pre>
   *
   * <code>int64 updateTime = 4;</code>
   * @return The updateTime.
   */
  long getUpdateTime();

  /**
   * <pre>
   *VPC是否是当前region的默认VPC
   * </pre>
   *
   * <code>bool isDefault = 5;</code>
   * @return The isDefault.
   */
  boolean getIsDefault();

  /**
   * <pre>
   *VPC的网段
   * </pre>
   *
   * <code>string cidr = 6;</code>
   * @return The cidr.
   */
  java.lang.String getCidr();
  /**
   * <pre>
   *VPC的网段
   * </pre>
   *
   * <code>string cidr = 6;</code>
   * @return The bytes for cidr.
   */
  com.google.protobuf.ByteString
      getCidrBytes();

  /**
   * <pre>
   *region信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.RegionInfo region = 7;</code>
   * @return Whether the region field is set.
   */
  boolean hasRegion();
  /**
   * <pre>
   *region信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.RegionInfo region = 7;</code>
   * @return The region.
   */
  com.didiyun.base.v1.RegionInfo getRegion();
  /**
   * <pre>
   *region信息
   * </pre>
   *
   * <code>.didi.cloud.base.v1.RegionInfo region = 7;</code>
   */
  com.didiyun.base.v1.RegionInfoOrBuilder getRegionOrBuilder();

  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 8;</code>
   * @return Whether the job field is set.
   */
  boolean hasJob();
  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 8;</code>
   * @return The job.
   */
  com.didiyun.base.v1.JobInfo getJob();
  /**
   * <pre>
   *任务
   * </pre>
   *
   * <code>.didi.cloud.base.v1.JobInfo job = 8;</code>
   */
  com.didiyun.base.v1.JobInfoOrBuilder getJobOrBuilder();
}
