// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base/v1/base.proto

package com.didiyun.base.v1;

public interface ErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.base.v1.Error)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *错误码
   * </pre>
   *
   * <code>int32 errno = 1;</code>
   * @return The errno.
   */
  int getErrno();

  /**
   * <pre>
   *错误信息
   * </pre>
   *
   * <code>string errmsg = 2;</code>
   * @return The errmsg.
   */
  java.lang.String getErrmsg();
  /**
   * <pre>
   *错误信息
   * </pre>
   *
   * <code>string errmsg = 2;</code>
   * @return The bytes for errmsg.
   */
  com.google.protobuf.ByteString
      getErrmsgBytes();

  /**
   * <pre>
   *请求ID
   * </pre>
   *
   * <code>string requestId = 3;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <pre>
   *请求ID
   * </pre>
   *
   * <code>string requestId = 3;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();
}
