// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base/v1/base.proto

package com.didiyun.base.v1;

public interface HeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.base.v1.Header)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string regionId = 1;</code>
   * @return The regionId.
   */
  java.lang.String getRegionId();
  /**
   * <code>string regionId = 1;</code>
   * @return The bytes for regionId.
   */
  com.google.protobuf.ByteString
      getRegionIdBytes();

  /**
   * <code>string zoneId = 2;</code>
   * @return The zoneId.
   */
  java.lang.String getZoneId();
  /**
   * <code>string zoneId = 2;</code>
   * @return The bytes for zoneId.
   */
  com.google.protobuf.ByteString
      getZoneIdBytes();
}
