// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base/v1/base.proto

package com.didiyun.base.v1;

public interface RegionAndZoneInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:didi.cloud.base.v1.RegionAndZoneInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string areaName = 3;</code>
   * @return The areaName.
   */
  java.lang.String getAreaName();
  /**
   * <code>string areaName = 3;</code>
   * @return The bytes for areaName.
   */
  com.google.protobuf.ByteString
      getAreaNameBytes();

  /**
   * <code>.didi.cloud.base.v1.ZoneInfo zone = 5;</code>
   * @return Whether the zone field is set.
   */
  boolean hasZone();
  /**
   * <code>.didi.cloud.base.v1.ZoneInfo zone = 5;</code>
   * @return The zone.
   */
  com.didiyun.base.v1.ZoneInfo getZone();
  /**
   * <code>.didi.cloud.base.v1.ZoneInfo zone = 5;</code>
   */
  com.didiyun.base.v1.ZoneInfoOrBuilder getZoneOrBuilder();
}
